// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         meetingKey: "meetingKey"
 *     }
 */
export interface DeleteV2MeetingsMeetingKeyRequest {
    meetingKey: string;
}
