// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         boxKey: "boxKey"
 *     }
 */
export interface GetV2BoxesBoxKeyMeetingsRequest {
    boxKey: string;
    /** Number of items to return. */
    limit?: number;
    /** Zero-based page number */
    page?: number;
}
