// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         boxKey: "boxKey",
 *         meetingType: "CALL_LOG",
 *         startTimestamp: 1646870400000
 *     }
 */
export interface MeetingCreateBody {
    boxKey: string;
    /** Meeting type. */
    meetingType: Streak.MeetingType;
    /** Meeting start timestamp, in epoch milliseconds. */
    startTimestamp: number;
    /** Meeting duration in milliseconds. */
    duration?: number;
    /** Meeting notes. */
    notes?: string | null;
    /** Task keys associated with this meeting. */
    taskKeys?: string[] | null;
    /** Whether this meeting is a draft. */
    isDraft?: boolean;
}
