// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         meetingKey: "meetingKey"
 *     }
 */
export interface MeetingUpdateBody {
    meetingKey: string;
    /** New meeting type. Omit this field to keep the existing meeting type unchanged. */
    meetingType?: string | null;
    /** New meeting start timestamp, in epoch milliseconds. Omit this field to keep the existing start time unchanged. */
    startTimestamp?: number | null;
    /** New meeting duration in milliseconds. Omit this field to keep the existing duration unchanged. */
    duration?: number | null;
    /** New meeting notes. Omit this field to keep the existing notes unchanged. */
    notes?: string | null;
    /** Whether to publish a draft meeting. Omit this field to keep the existing draft state unchanged. */
    isDraft?: boolean | null;
    /** Replacement task keys associated with this meeting. Omit this field to keep existing task keys unchanged. */
    taskKeys?: string[] | null;
}
