configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/streak%2Fstreak-5262bf1d717cbfea459e3d7ed574be7c0b64977aed25a81ffadc3d1b0b1e4944.yml
openapi_spec_hash: 62c5f4da4781f96cd20fcb7fd1cf2bd5
config_hash: 3dcf47bcf0ad5232c571585fe9f76beb
