// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         apiKeyKey: "apiKeyKey"
 *     }
 */
export interface DeleteV1ApikeysApiKeyKeyRequest {
    apiKeyKey: string;
}
