// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetV1ApikeysRequest {
    /** Number of items to return. */
    limit?: number;
    /** Zero-based page number */
    page?: number;
}
