// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         pipelineKey: "pipelineKey"
 *     }
 */
export interface GetV1PipelinesPipelineKeyFieldsRequest {
    pipelineKey: string;
}
