// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         pipelineKey: "pipelineKey",
 *         fieldKey: "fieldKey"
 *     }
 */
export interface GetV1PipelinesPipelineKeyFieldsFieldKeyRequest {
    pipelineKey: string;
    fieldKey: string;
}
