// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         teamKey: "teamKey",
 *         stages: ["stages"]
 *     }
 */
export interface PipelineCreate {
    /** Pipeline name. */
    name: string;
    /** Key for the team that will own the pipeline. */
    teamKey: string;
    /** Stage names in display order. */
    stages: string[];
    /** Pipeline icon name. */
    icon?: string | null;
    /** Pipeline description. */
    description?: string | null;
    /** Template identifier associated with the pipeline. */
    templateType?: string | null;
    /** Fields to create in the pipeline. */
    fields?: Streak.PipelineFieldCreate[] | null;
    /** Default permission set for users without an explicit assignment. */
    defaultPermissionSetName?: string | null;
    /** Whether sharing is restricted to members of the owning team. */
    sharingRestrictedToTeam?: boolean | null;
}
