// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         pipelineKey: "pipelineKey"
 *     }
 */
export interface PipelineUpdate {
    pipelineKey: string;
    /** New team key. Omit to keep the current team. */
    teamKey?: string | null;
    /** New icon. Omit to keep the current icon. */
    icon?: string | null;
    /** New name. Omit to keep the current name. */
    name?: string | null;
    /** New description. Omit to keep the current description. */
    description?: string | null;
    /** New team sharing restriction. Omit to keep the current value. */
    sharingRestrictedToTeam?: boolean | null;
    /** Complete stage order. Omit to keep the current order; an empty list is invalid. */
    stageOrder?: string[] | null;
    /** New stage color theme. Omit to keep the current theme. */
    stageColorTheme?: string | null;
    /** Replacement custom permission sets. Omit to keep existing sets. */
    customPermissionSets?: Record<string, Streak.PipelinePermissionSetInput | null> | null;
    /** New default permission set. Omit to keep the current value. */
    defaultPermissionSetName?: string | null;
    /** Replacement sharing entries. Omit to keep existing sharing; an empty list is invalid. */
    aclEntries?: Streak.PipelineSharingEntryInput[] | null;
}
