// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         pipelineKey: "pipelineKey",
 *         fieldKey: "fieldKey"
 *     }
 */
export interface PipelineFieldUpdate {
    pipelineKey: string;
    fieldKey: string;
    /** Append dropdown or tag options while retaining existing options. Defaults to false. */
    addOnly?: boolean;
    /** New field name. */
    name?: string | null;
    /** New default value or formula. */
    defaultValue?: string | null;
    /** Dropdown options to apply. */
    dropdownSettings?: Streak.PipelineFieldDropdownSettingsUpdate | null;
    /** Tag options to apply. */
    tagSettings?: Streak.PipelineFieldTagSettingsUpdate | null;
    /** AI settings to update. */
    aiSettings?: Streak.PipelineFieldAiSettingsUpdate | null;
}
