// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         pipelineKey: "pipelineKey",
 *         body: {
 *             name: "name",
 *             type: "TEXT_INPUT"
 *         }
 *     }
 */
export interface PostV2PipelinesPipelineKeyFieldsRequest {
    pipelineKey: string;
    body: Streak.PipelineFieldCreate;
}
