// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         taskKey: "taskKey"
 *     }
 */
export interface DeleteV2TasksTaskKeyRequest {
    /** Key for the task to delete. */
    taskKey: string;
}
