// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         boxKey: "boxKey"
 *     }
 */
export interface GetV2BoxesBoxKeyTasksRequest {
    /** Key for the box whose tasks should be listed. */
    boxKey: string;
    /** Number of items to return. Maximum: 1000 */
    limit?: number;
    /** Zero-based page number */
    page?: number;
}
