// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         taskKey: "taskKey"
 *     }
 */
export interface GetV2TasksTaskKeyRequest {
    /** Key for the task to return. */
    taskKey: string;
}
