// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetV2TasksRequest {
    /** Agenda direction. Accepted values are desc, past, asc, and future. Defaults to desc. */
    direction?: string | null;
    /** Whether completed tasks should be included in the returned agenda. */
    includeCompleted?: boolean;
    /** Maximum number of tasks to return per assigned user. */
    limit?: number;
    /** Key for the pipeline to filter tasks to. Omit to search across all visible pipelines. */
    pipelineKey?: string | null;
    /** Opaque 30-digit sort cursor returned as task.sortOrder. Omit to use tomorrow at local midnight as the cursor boundary. */
    sortOrder?: string | null;
    /** User keys whose assigned tasks should be returned. Omit to return tasks assigned to the current user. */
    userKeys?: string[] | null;
}
