// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         boxKey: "boxKey",
 *         text: "text"
 *     }
 */
export interface TaskCreateBody {
    /** Key for the box to create the task on. */
    boxKey: string;
    /** Task text. */
    text: string;
    /** Task due date, in epoch milliseconds. Use -1 to create a task with no due date. */
    dueDate?: number | null;
    /** Users to assign to this task. Omit to assign the task to the creator. */
    assignedTo?: Streak.AssigneeInput[] | null;
    /** Key for the meeting this task belongs to, when any. */
    meetingKey?: string | null;
    /** Whether to create this task as a draft. Draft tasks do not send notifications or webhooks. */
    isDraft?: boolean | null;
    /** Key for the contact used to infer suggested task actions. */
    teamContactKey?: string | null;
    draft?: boolean;
}
