// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         taskKey: "taskKey"
 *     }
 */
export interface TaskUpdateBody {
    /** Key for the task to update. */
    taskKey: string;
    /** New task text. Omit this field to keep existing text unchanged. */
    text?: string | null;
    /** New task due date, in epoch milliseconds. Use -1 to clear the due date. */
    dueDate?: number | null;
    /** New task completion status. Omit this field to keep existing status unchanged. */
    status?: string | null;
    /** Replacement users assigned to this task. Omit this field to keep existing assignees unchanged. */
    assignedTo?: Streak.AssigneeInput[] | null;
    /** Key for the meeting this task belongs to. Omit this field to keep existing meeting unchanged. */
    meetingKey?: string | null;
    /** Whether to publish a draft task. Omit this field to keep existing draft state unchanged. */
    isDraft?: boolean | null;
    draft?: boolean;
}
