// This file was auto-generated by Fern from our API Definition.

export const Action = {
    Get: "GET",
    Update: "UPDATE",
    Delete: "DELETE",
    Create: "CREATE",
    ChangePermissions: "CHANGE_PERMISSIONS",
    ChangeAdmins: "CHANGE_ADMINS",
    SetTeam: "SET_TEAM",
    RestrictSharing: "RESTRICT_SHARING",
    OverrideSharingRestriction: "OVERRIDE_SHARING_RESTRICTION",
    OverrideValidator: "OVERRIDE_VALIDATOR",
    Resize: "RESIZE",
    Hide: "HIDE",
    Freeze: "FREEZE",
    Options: "OPTIONS",
    Format: "FORMAT",
    Order: "ORDER",
    Summary: "SUMMARY",
    Export: "EXPORT",
    FlowPauseResume: "FLOW_PAUSE_RESUME",
    FlowViewLogs: "FLOW_VIEW_LOGS",
    GetBoxes: "GET_BOXES",
} as const;
export type Action = (typeof Action)[keyof typeof Action];
