// This file was auto-generated by Fern from our API Definition.

export const ActionType = {
    Email: "EMAIL",
    Schedule: "SCHEDULE",
    Call: "CALL",
    FollowUp: "FOLLOW_UP",
} as const;
export type ActionType = (typeof ActionType)[keyof typeof ActionType];
