// This file was auto-generated by Fern from our API Definition.

export const ActivitySourceType = {
    Human: "HUMAN",
    SystemOnboarding: "SYSTEM_ONBOARDING",
    AiPipelineCreator: "AI_PIPELINE_CREATOR",
} as const;
export type ActivitySourceType = (typeof ActivitySourceType)[keyof typeof ActivitySourceType];
