// This file was auto-generated by Fern from our API Definition.

export const ApiKeyType = {
    User: "USER",
    Team: "TEAM",
} as const;
export type ApiKeyType = (typeof ApiKeyType)[keyof typeof ApiKeyType];
