// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface ApiKey {
    /** The API key secret value. */
    apiKey: string;
    /** Key for this API key. */
    key: string;
    /** Timestamp when this API key was created, in epoch milliseconds. */
    creationTimestamp: number;
    /** Timestamp when the last time this key was modified, in epoch milliseconds. */
    lastSavedTimestamp: number;
    /** Whether this key authenticates one user or can impersonate members of a team. */
    keyType: Streak.ApiKeyType;
    /** Team this key can impersonate members of. Only present for team keys. */
    teamKey?: (string | null) | undefined;
}
