// This file was auto-generated by Fern from our API Definition.

/**
 * Assignee identified by user key or email address. At least one must be provided. If both are specified, userKey takes precedence.
 */
export interface AssigneeInput {
    /** Key for the assigned user. Takes precedence when both userKey and email are specified. */
    userKey?: (string | null) | undefined;
    /** Email address for the assigned user. Required when userKey is omitted. */
    email?: (string | null) | undefined;
}
