// This file was auto-generated by Fern from our API Definition.

export const AutofillSource = {
    BoxTimeline: "BOX_TIMELINE",
    WebCrawling: "WEB_CRAWLING",
} as const;
export type AutofillSource = (typeof AutofillSource)[keyof typeof AutofillSource];
