// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A wrapper for a list of Comment(s) that supports paging when available.
 */
export interface CommentListResponse {
    /** Whether there are more Comment(s) available after this response. */
    hasNextPage?: boolean | undefined;
    /** The Comment(s) returned by this response. */
    results: Streak.Comment[];
}
