// This file was auto-generated by Fern from our API Definition.

export interface CommentMention {
    /** Key for the mentioned user. */
    userKey: string;
    /** Zero-based character offset where the mention starts. */
    offset?: number | undefined;
    /** Character length of the mention. */
    length?: number | undefined;
}
