// This file was auto-generated by Fern from our API Definition.

export interface CommentMentionBody {
    /** Key for the mentioned user. */
    userKey: string;
    /** Mention start offset in the comment text. */
    offset?: number | undefined;
    /** Mention length in the comment text. */
    length?: number | undefined;
}
