// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface CommentReactionSummary {
    /** Emoji used for this reaction group. */
    emoji: string;
    /** Number of users who reacted with this emoji. */
    count?: number | undefined;
    /** Users who reacted with this emoji, ordered by oldest reaction first. */
    users: Streak.UserBrief[];
}
