// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface Comment {
    /** Key for this comment. */
    key: string;
    /** Key for the box this comment belongs to. */
    boxKey: string;
    /** Key for the pipeline this comment belongs to. */
    pipelineKey: string;
    /** Key for the user who created this comment. */
    creatorKey: string;
    /** Key for the newsfeed entry created for this comment. */
    newsfeedEntryKey?: (string | null) | undefined;
    /** Timestamp when the comment was created, in epoch milliseconds. */
    timestamp?: (number | null) | undefined;
    /** Comment text. */
    message?: (string | null) | undefined;
    /** User mentions found in the comment text. */
    mentions?: (Streak.CommentMention[] | null) | undefined;
    /** Key for the parent comment, when this comment is a reply. */
    parent?: (string | null) | undefined;
    /** Keys for this comment's direct replies. */
    children?: (string[] | null) | undefined;
    /** Emoji reactions grouped by emoji. */
    reactionSummary: Streak.CommentReactionSummary[];
    /** Timestamp when the comment was last persisted, in epoch milliseconds. */
    lastSavedTimestamp?: (number | null) | undefined;
}
