// This file was auto-generated by Fern from our API Definition.

/**
 * A relationship to a contact.
 */
export interface ContactLink {
    /** Key for the linked contact. */
    key: string;
    /** Whether Streak linked this record automatically. */
    isMagicLinked?: boolean | undefined;
    /** Time the relationship was created, in epoch milliseconds. */
    creationTimestamp?: (number | null) | undefined;
}
