// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A contact shared with the team.
 */
export interface Contact {
    /** Stable key for this contact. */
    key: string;
    /** Key for the team that owns this contact. */
    teamKey: string;
    /** Given name of the contact. */
    givenName?: (string | null) | undefined;
    /** Family name of the contact. */
    familyName?: (string | null) | undefined;
    /** Notes about the contact. */
    other?: (string | null) | undefined;
    /** Job title of the contact. */
    title?: (string | null) | undefined;
    /** Normalized email addresses with duplicates removed, in first-occurrence order. */
    emailAddresses: string[];
    /** Phone numbers with duplicates and null entries removed, in first-occurrence order. */
    phoneNumbers: string[];
    /** Postal addresses with duplicates and null entries removed, in first-occurrence order. */
    addresses: string[];
    /** Website domains associated with the contact. */
    domains: string[];
    /** Stored normalized domains used to match organizations. */
    normalizedDomains: string[];
    /** Twitter profile handle. */
    twitterHandle?: (string | null) | undefined;
    /** Facebook profile handle. */
    facebookHandle?: (string | null) | undefined;
    /** LinkedIn profile handle. */
    linkedinHandle?: (string | null) | undefined;
    /** Instagram profile handle. */
    instagramHandle?: (string | null) | undefined;
    /** URL of the contact profile image. */
    photoUrl?: (string | null) | undefined;
    /** Key for the user who last edited this record. */
    lastSavedUserKey?: (string | null) | undefined;
    /** Key for the user who created this record. */
    creatorKey?: (string | null) | undefined;
    /** Time this record was first created, in epoch milliseconds. */
    creationDate?: (number | null) | undefined;
    /** Time this version of the record was created, in epoch milliseconds. */
    versionTimestamp?: (number | null) | undefined;
    /** Time this record was last saved, in epoch milliseconds. */
    lastSavedTimestamp?: (number | null) | undefined;
    /** Time enrichment was last applied or reviewed, in epoch milliseconds. */
    lastEnrichmentTimestamp?: (number | null) | undefined;
    /** Contacts linked to this record, in their stored order. */
    contactLinks: Streak.ContactLink[];
    /** Organizations linked to this record, in their stored order. */
    orgLinks: Streak.OrganizationLink[];
    /** Custom field values keyed by field identifier. */
    fields: Record<string, string>;
}
