// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A page of contact records and its continuation cursor.
 */
export interface ContactPage {
    /** Records in this page, in result order. */
    results: Streak.Contact[];
    /** Opaque cursor to pass to the next page request, when present. */
    cursor?: (string | null) | undefined;
}
