// This file was auto-generated by Fern from our API Definition.

export const EmailSharing = {
    None: "None",
    Existence: "Existence",
} as const;
export type EmailSharing = (typeof EmailSharing)[keyof typeof EmailSharing];
