// This file was auto-generated by Fern from our API Definition.

export const FieldType = {
    TextInput: "TEXT_INPUT",
    Dropdown: "DROPDOWN",
    Checkbox: "CHECKBOX",
    Date: "DATE",
    Person: "PERSON",
    Formula: "FORMULA",
    Tag: "TAG",
    TeamContact: "TEAM_CONTACT",
    TeamOrganization: "TEAM_ORGANIZATION",
} as const;
export type FieldType = (typeof FieldType)[keyof typeof FieldType];
