// This file was auto-generated by Fern from our API Definition.

export const InviteStatus = {
    Pending: "Pending",
    Accepted: "Accepted",
} as const;
export type InviteStatus = (typeof InviteStatus)[keyof typeof InviteStatus];
