// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface Meeting {
    /** Key for this meeting. */
    key: string;
    /** Key for the box this meeting belongs to. */
    boxKey: string;
    /** Key for the pipeline this meeting belongs to. */
    pipelineKey: string;
    /** Key for the user who created this meeting. */
    creatorKey: string;
    /** Whether this meeting is a draft. */
    isDraft?: boolean | undefined;
    /** Task keys associated with this meeting. */
    taskKeys: string[];
    /** Timestamp when this meeting was created, in epoch milliseconds. */
    creationDate: number;
    /** Meeting type. */
    meetingType: Streak.MeetingType;
    /** Meeting start timestamp, in epoch milliseconds. */
    startTimestamp: number;
    /** Meeting duration in milliseconds. */
    duration?: number | undefined;
    /** Meeting notes. */
    notes: string;
    /** Timestamp when this meeting was last persisted, in epoch milliseconds. */
    lastSavedTimestamp: number;
}
