// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A wrapper for a list of Meeting(s) that supports paging when available.
 */
export interface MeetingListResponse {
    /** Whether there are more Meeting(s) available after this response. */
    hasNextPage?: boolean | undefined;
    /** The Meeting(s) returned by this response. */
    results: Streak.Meeting[];
}
