// This file was auto-generated by Fern from our API Definition.

export const MeetingType = {
    CallLog: "CALL_LOG",
    MeetingNotes: "MEETING_NOTES",
} as const;
export type MeetingType = (typeof MeetingType)[keyof typeof MeetingType];
