// This file was auto-generated by Fern from our API Definition.

export interface OperationResponse {
    /** Whether the operation completed successfully. */
    success?: boolean | undefined;
    /** A message describing the result of the operation. */
    message?: (string | null) | undefined;
}
