// This file was auto-generated by Fern from our API Definition.

/**
 * A relationship to an organization.
 */
export interface OrganizationLinkInput {
    /** Key of the related organization. */
    key: string;
    /** Whether the relationship was created automatically. */
    isMagicLinked?: boolean | undefined;
    /** Relationship creation timestamp, in epoch milliseconds, when known. */
    creationTimestamp?: (number | null) | undefined;
}
