// This file was auto-generated by Fern from our API Definition.

/**
 * A relationship to an organization.
 */
export interface OrganizationLink {
    /** Stable key for the linked organization. */
    key: string;
    /** Whether Streak linked this record automatically. */
    isMagicLinked?: boolean | undefined;
    /** Time the relationship was created, in epoch milliseconds. */
    creationTimestamp?: (number | null) | undefined;
}
