// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * An organization shared with the team.
 */
export interface Organization {
    /** Stable key for this organization. */
    key: string;
    /** Key for the team that owns this organization. */
    teamKey: string;
    /** Name of the organization. */
    name?: (string | null) | undefined;
    /** Notes about the organization. */
    other?: (string | null) | undefined;
    /** Website domains in their stored order. */
    domains: string[];
    /** Stored normalized website domains. */
    normalizedDomains: string[];
    /** Industry of the organization. */
    industry?: (string | null) | undefined;
    /** Phone numbers in their stored order. */
    phoneNumbers: string[];
    /** Postal addresses in their stored order. */
    addresses: string[];
    /** Employee count or range as text. */
    employeeCount?: (string | null) | undefined;
    /** URL of the organization logo. */
    logoURL?: (string | null) | undefined;
    /** Twitter profile handle. */
    twitterHandle?: (string | null) | undefined;
    /** Facebook profile handle. */
    facebookHandle?: (string | null) | undefined;
    /** LinkedIn profile handle. */
    linkedinHandle?: (string | null) | undefined;
    /** Instagram profile handle. */
    instagramHandle?: (string | null) | undefined;
    /** Key for the user who last edited this record. */
    lastSavedUserKey?: (string | null) | undefined;
    /** Key for the user who created this record. */
    creatorKey?: (string | null) | undefined;
    /** Time this record was first created, in epoch milliseconds. */
    creationDate?: (number | null) | undefined;
    /** Time this version of the record was created, in epoch milliseconds. */
    versionTimestamp?: (number | null) | undefined;
    /** Time this record was last saved, in epoch milliseconds. */
    lastSavedTimestamp?: (number | null) | undefined;
    /** Time enrichment was last applied or reviewed, in epoch milliseconds. */
    lastEnrichmentTimestamp?: (number | null) | undefined;
    /** Contacts linked to this record, in their stored order. */
    contactLinks: Streak.ContactLink[];
    /** Organizations linked to this record, in their stored order. */
    orgLinks: Streak.OrganizationLink[];
    /** Custom field values keyed by field identifier. */
    fields: Record<string, string>;
}
