// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface PipelineFieldCreate {
    /** Field name. */
    name: string;
    /** Field data type. */
    type: Streak.FieldType;
    /** Initial default value. Currently only used for formula fields. */
    defaultValue?: (string | null) | undefined;
}
