// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface Pipeline {
    /** Key for this pipeline. */
    key: string;
    /** Key for the team that owns this pipeline. */
    teamKey?: (string | null) | undefined;
    /** Key for the user who created this pipeline. */
    creatorKey: string;
    /** Pipeline name. */
    name: string;
    /** Pipeline icon name. */
    icon: string;
    /** Pipeline description. */
    description?: (string | null) | undefined;
    /** Whether sharing is restricted to the team. */
    sharingRestrictedToTeam?: (boolean | null) | undefined;
    /** Custom fields configured for this pipeline. */
    fields: Streak.PipelineField[];
    /** Stages in this pipeline, keyed by stage key. */
    stages: Record<string, Streak.PipelineStage>;
    /** The display order of the stages */
    stageOrder: string[];
    /** Color theme used for stages without custom colors. */
    stageColorTheme: Streak.WorkflowTheme;
    /** Timestamp when the pipeline was created, in epoch milliseconds. */
    creationTimestamp: number;
    /** Timestamp when the pipeline was last updated, in epoch milliseconds. */
    lastUpdatedTimestamp: number;
    /** Latest formula-definition update timestamp, in epoch milliseconds. */
    formulasLastUpdatedTimestamp?: (number | null) | undefined;
    /** Custom permission sets configured for this pipeline. */
    customPermissionSets: Record<string, Streak.PipelinePermissionSet>;
    /** Default permission set assigned to users without an explicit assignment. */
    defaultPermissionSetName: string;
    /** Users explicitly sharing this pipeline and their permission assignments. */
    aclEntries: Streak.PipelineSharingEntry[];
    /** Source that created the pipeline. */
    creationSourceType: Streak.ActivitySourceType;
    /** Current number of boxes in the pipeline. */
    boxCount?: number | undefined;
    /** Timestamp when the pipeline was last persisted, in epoch milliseconds. */
    lastSavedTimestamp: number;
}
