// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface PipelineDropdownSettings {
    /** Available dropdown options. */
    items: Streak.PipelineDropdownItem[];
}
