// This file was auto-generated by Fern from our API Definition.

/**
 * An existing or new tag option.
 */
export interface PipelineFieldTagItemUpdate {
    /** Existing tag key. Omit the key when adding a tag. */
    key?: (string | null) | undefined;
    /** Nonempty tag label. */
    tag?: (string | null) | undefined;
}
