// This file was auto-generated by Fern from our API Definition.

/**
 * An existing or new dropdown option.
 */
export interface PipelineFieldDropdownItemUpdate {
    /** Existing option key. Omit the key when adding an option. */
    key?: (string | null) | undefined;
    /** Nonempty option label. */
    name?: (string | null) | undefined;
}
