// This file was auto-generated by Fern from our API Definition.

/**
 * Changes to AI settings.
 */
export interface PipelineFieldAiSettingsUpdate {
    /** AI prompt. An empty string clears it. */
    prompt?: (string | null) | undefined;
    /** Content used for AI autofill. */
    source?: (string | null) | undefined;
}
