// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A wrapper for a list of Pipeline(s) that supports paging when available.
 */
export interface PipelineListResponse {
    /** Whether there are more Pipeline(s) available after this response. */
    hasNextPage?: boolean | undefined;
    /** The Pipeline(s) returned by this response. */
    results: Streak.Pipeline[];
}
