// This file was auto-generated by Fern from our API Definition.

export interface PipelineDropdownItem {
    /** Option key. */
    key?: (string | null) | undefined;
    /** Option name. */
    name: string;
}
