// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface PipelineTagSettings {
    /** Available tags. */
    tags: Streak.PipelineTagItem[];
}
