// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Tag options in the requested order.
 */
export interface PipelineFieldTagSettingsUpdate {
    /** Tags to keep or add. An empty list removes all tags unless addOnly is true. */
    tags?: (Streak.PipelineFieldTagItemUpdate[] | null) | undefined;
}
