// This file was auto-generated by Fern from our API Definition.

export interface PipelineSharingEntry {
    /** Key for the shared user. */
    userKey: string;
    /** Permission set assigned to the user. */
    permissionSetName: string;
    /** User email address. */
    email?: (string | null) | undefined;
    /** User display name. */
    displayName?: (string | null) | undefined;
    /** User full name. */
    fullName?: (string | null) | undefined;
    /** User given name. */
    givenName?: (string | null) | undefined;
    /** User profile image URL. */
    image?: (string | null) | undefined;
    /** User account type. */
    userType?: (string | null) | undefined;
    /** Whether the sharing entry is read-only. */
    isReadOnly?: (boolean | null) | undefined;
}
