// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface PipelinePermissionInput {
    /** Entity type governed by the permission. */
    entityType: string;
    /** Action granted by the permission. */
    action: Streak.Action;
    /** Condition that must be satisfied for the permission to apply. */
    conditionalCheck: Streak.PipelineConditionalCheck;
    /** Additional parameters used by the conditional check. */
    params?: (Record<string, string | null> | null) | undefined;
}
