// This file was auto-generated by Fern from our API Definition.

/** Condition required for a permission to apply. NONE has no additional condition; ASSIGNED_TO and CREATOR match the user to the entity; BOX_UPDATE and BOX_VIEW require the corresponding permission on the containing pipeline item; UNARCHIVED requires an unarchived item. FIELD_COMPARISON and STAGE are reserved and currently unsupported. */
export const PipelineConditionalCheck = {
    None: "NONE",
    AssignedTo: "ASSIGNED_TO",
    FieldComparison: "FIELD_COMPARISON",
    Stage: "STAGE",
    Creator: "CREATOR",
    BoxUpdate: "BOX_UPDATE",
    BoxView: "BOX_VIEW",
    Unarchived: "UNARCHIVED",
} as const;
export type PipelineConditionalCheck = (typeof PipelineConditionalCheck)[keyof typeof PipelineConditionalCheck];
