// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface PipelineStage {
    /** Stage key within the pipeline. */
    key: string;
    /** Stage name. */
    name: string;
    /** Stage color. */
    color: Streak.PipelineStageColor;
    /** Whether the color is inherited from the pipeline theme. */
    isColorFromTheme?: boolean | undefined;
    /** Number of boxes currently in this stage. */
    boxCount?: number | undefined;
}
