// This file was auto-generated by Fern from our API Definition.

export interface PipelineSharingEntryInput {
    /** Key for the user to share with. Takes precedence over email when both are provided. */
    userKey?: (string | null) | undefined;
    /** Email address used to find or create the user when userKey is omitted. */
    email?: (string | null) | undefined;
    /** Permission set to assign to the user. */
    permissionSetName: string;
}
