// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface PipelineField {
    /** Field key within the pipeline. */
    key: string;
    /** Field name. */
    name: string;
    /** Field data type. */
    type: Streak.FieldType;
    /** Default value for this field. */
    defaultValue?: unknown | undefined;
    /** Timestamp when the default value last changed, in epoch milliseconds. */
    lastDefaultValueUpdatedTimestamp?: (number | null) | undefined;
    /** Timestamp when this field last changed, in epoch milliseconds. */
    lastUpdatedTimestamp?: (number | null) | undefined;
    /** Dropdown options when this is a dropdown field. */
    dropdownSettings?: (Streak.PipelineDropdownSettings | null) | undefined;
    /** Tag options when this is a tag field. */
    tagSettings?: (Streak.PipelineTagSettings | null) | undefined;
    /** AI autofill settings for this field. */
    aiSettings: Streak.PipelineAiSettings;
}
