// This file was auto-generated by Fern from our API Definition.

/** Content used as context for AI autofill. BOX_TIMELINE uses the pipeline item's timeline; WEB_CRAWLING uses content found on the web. */
export const PipelineAutofillSource = {
    BoxTimeline: "BOX_TIMELINE",
    WebCrawling: "WEB_CRAWLING",
} as const;
export type PipelineAutofillSource = (typeof PipelineAutofillSource)[keyof typeof PipelineAutofillSource];
