// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Dropdown options in the requested order.
 */
export interface PipelineFieldDropdownSettingsUpdate {
    /** Options to keep or add. An empty list removes all options unless addOnly is true. */
    items?: (Streak.PipelineFieldDropdownItemUpdate[] | null) | undefined;
}
