// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface PipelineAiSettings {
    /** Prompt used for AI autofill. */
    prompt: string;
    /** Content used as context for AI autofill. */
    source: Streak.PipelineAutofillSource;
}
