// This file was auto-generated by Fern from our API Definition.

export interface PipelineStageColor {
    /** Foreground color as a CSS color string. */
    foregroundColor: string;
    /** Background color as a CSS color string. */
    backgroundColor: string;
}
