// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface PipelinePermissionSet {
    /** Permissions granted by this set. */
    permissions: Streak.PipelinePermission[];
    /** Whether users may be assigned this permission set. */
    userAssignable?: boolean | undefined;
}
