// This file was auto-generated by Fern from our API Definition.

export const ReminderStatus = {
    None: "NONE",
    Scheduled: "SCHEDULED",
    Reminded: "REMINDED",
    ErrorOnReminder: "ERROR_ON_REMINDER",
    NotRemindedBecauseTaskDone: "NOT_REMINDED_BECAUSE_TASK_DONE",
} as const;
export type ReminderStatus = (typeof ReminderStatus)[keyof typeof ReminderStatus];
