// This file was auto-generated by Fern from our API Definition.

export const Role = {
    Member: "Member",
    Owner: "Owner",
    PayerOnly: "PayerOnly",
    ArchiveOnly: "ArchiveOnly",
} as const;
export type Role = (typeof Role)[keyof typeof Role];
