// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Response returned by the legacy v1 search endpoint.
 */
export interface SearchResponse {
    /** Search results grouped by entity type. */
    results: Streak.SearchResults;
    /** The query string used for full-text searches. Null when searching by exact box name. */
    query?: (string | null) | undefined;
    /** Zero-based page number returned by the search. */
    page?: number | undefined;
}
