// This file was auto-generated by Fern from our API Definition.

/**
 * Box result returned by the v1 search endpoint.
 */
export interface SearchBoxResult {
    /** Key for the matching box. */
    boxKey: string;
    /** Box name. */
    name?: (string | null) | undefined;
    /** Timestamp when the box was last updated, in epoch milliseconds. */
    lastUpdatedTimestamp?: number | undefined;
    /** User keys assigned to the box. */
    assignedToKeys?: (string[] | null) | undefined;
    /** Current stage key for the box. */
    stageKey?: (string | null) | undefined;
    /** Pipeline key for the box. */
    pipelineKey?: (string | null) | undefined;
}
