// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Search results grouped by legacy result collection name.
 */
export interface SearchResults {
    /** Matching boxes. */
    boxes: Streak.SearchBoxResult[];
    /** Matching contacts. */
    contacts: Streak.SearchContactResult[];
    /** Matching organizations. */
    orgs: Streak.SearchOrganizationResult[];
}
