// This file was auto-generated by Fern from our API Definition.

/**
 * Contact result returned by the v1 search endpoint.
 */
export interface SearchContactResult {
    /** Contact given name. */
    givenName?: (string | null) | undefined;
    /** Contact family name. */
    familyName?: (string | null) | undefined;
    /** Contact display name or other indexed text. */
    other?: (string | null) | undefined;
    /** Key for the matching contact. */
    key?: (string | null) | undefined;
    /** Contact title. */
    title?: (string | null) | undefined;
    /** Contact street addresses. */
    addresses?: (string[] | null) | undefined;
    /** Contact email addresses. */
    emailAddresses?: (string[] | null) | undefined;
    /** Contact phone numbers. */
    phoneNumbers?: (string[] | null) | undefined;
}
