// This file was auto-generated by Fern from our API Definition.

/**
 * Organization result returned by the v1 search endpoint.
 */
export interface SearchOrganizationResult {
    /** Organization name. */
    name?: (string | null) | undefined;
    /** Organization display name or other indexed text. */
    other?: (string | null) | undefined;
    /** Key for the matching organization. */
    key?: (string | null) | undefined;
    /** Organization industry. */
    industry?: (string | null) | undefined;
    /** Organization employee count label. */
    employeeCount?: (string | null) | undefined;
    /** Organization logo URL. */
    logoURL?: (string | null) | undefined;
    /** Normalized organization domains. */
    normalizedDomains?: (string[] | null) | undefined;
    /** Organization domains. */
    domains?: (string[] | null) | undefined;
    /** Organization street addresses. */
    addresses?: (string[] | null) | undefined;
}
