// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Task attached to a box, including assignment, due date, status, and suggested actions.
 */
export interface Task {
    /** Key for this task. */
    key: string;
    /** Key for the box this task belongs to. */
    boxKey: string;
    /** Key for the pipeline this task belongs to. */
    pipelineKey: string;
    /** Key for the user who created this task. */
    creatorKey: string;
    /** The user who created this task. */
    creator: Streak.UserBrief;
    /** Users assigned to this task. Tasks created without explicit assignees are assigned to the creator by default. */
    assignedTo: Streak.UserBrief[];
    /** Timestamp when this task was created, in epoch milliseconds. */
    creationDate: number;
    /** Timestamp when this task was last persisted, in epoch milliseconds. */
    lastSavedTimestamp: number;
    /** Timestamp when this task status last changed, in epoch milliseconds. */
    lastStatusChangeDate: number;
    /** Task due date, in epoch milliseconds. */
    dueDate?: (number | null) | undefined;
    /** Task text. */
    text: string;
    /** Suggested actions inferred from the task text. */
    actions?: (Streak.TaskAction[] | null) | undefined;
    /** Task completion status. */
    status: Streak.TaskStatus;
    /** Task reminder status. */
    reminderStatus: Streak.ReminderStatus;
    /** Key for the meeting this task belongs to, when any. */
    meetingKey?: (string | null) | undefined;
}
