// This file was auto-generated by Fern from our API Definition.

export const TaskStatus = {
    NotDone: "NOT_DONE",
    Done: "DONE",
} as const;
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];
