// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A wrapper for a list of Task(s) that supports paging when available.
 */
export interface TaskListResponse {
    /** Whether there are more Task(s) available after this response. */
    hasNextPage?: boolean | undefined;
    /** The Task(s) returned by this response. */
    results: Streak.Task[];
}
