// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Suggested action inferred from task text.
 */
export interface TaskAction {
    /** Suggested action type. */
    type: Streak.ActionType;
    /** Suggested action value, such as an email address or phone number. */
    value: string;
    /** Contact this action is associated with. */
    contact: Streak.Contact;
}
