// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A wrapper for a list of Team(s) that supports paging when available.
 */
export interface TeamListResponse {
    /** Whether there are more Team(s) available after this response. */
    hasNextPage?: boolean | undefined;
    /** The Team(s) returned by this response. */
    results: Streak.Team[];
}
