// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Default and user-specific permissions for a system team list.
 */
export interface TeamBasedPermissions {
    /** Permission set applied to team members without an explicit override. */
    defaultPermissionSetName?: (string | null) | undefined;
    /** User permission overrides in the wire shape used by team sharing controls. */
    aclEntries: Streak.TeamAclEntry[];
}
