// This file was auto-generated by Fern from our API Definition.

/**
 * A team member's explicit permission for a system list.
 */
export interface TeamAclEntry {
    /** Key for the user receiving the permission. */
    userKey: string;
    /** Permission set assigned to the user. */
    permissionSetName: string;
    /** Whether the permission is fixed and cannot be edited by the requester. */
    isReadOnly?: boolean | undefined;
}
