// This file was auto-generated by Fern from our API Definition.

/**
 * One option in a team dropdown field.
 */
export interface TeamDropdownItem {
    /** Stable key for the option. */
    key: string;
    /** Display name for the option. */
    name: string;
}
