// This file was auto-generated by Fern from our API Definition.

/**
 * One member in a complete team-roster replacement.
 */
export interface TeamMemberUpdate {
    /** Existing user key. New invitations may supply email instead. */
    userKey?: (string | null) | undefined;
    /** Email address used to invite a user when no user key is supplied. */
    email?: (string | null) | undefined;
    /** Role for the team member. */
    role?: (string | null) | undefined;
    /** Invitation state for the team member. */
    inviteStatus?: (string | null) | undefined;
    /** Email visibility shared with the team. Allowed values are Existence and None. */
    emailSharing?: (string | null) | undefined;
}
