// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Partial permission update for one system team list.
 */
export interface TeamBasedPermissionsUpdate {
    /** New default permission set. Omit to leave the default unchanged. */
    defaultPermissionSetName?: (string | null) | undefined;
    /** Complete user override list. Omit to leave overrides unchanged; send an empty list to clear them. */
    aclEntries?: (Streak.TeamAclEntryUpdate[] | null) | undefined;
}
