// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A custom contact or organization field definition.
 */
export interface TeamField {
    /** Display name for the field. */
    name: string;
    /** Stable key for the field. */
    key: string;
    /** Data type stored by the field. */
    type: Streak.FieldType;
    /** Default textual field value, when one is configured. */
    defaultValue?: (string | null) | undefined;
    /** Timestamp when the default value last changed, in epoch milliseconds. */
    lastDefaultValueUpdatedTimestamp?: (number | null) | undefined;
    /** Timestamp when the field definition last changed, in epoch milliseconds. */
    lastUpdatedTimestamp?: (number | null) | undefined;
    /** Allowed dropdown options for a dropdown field. */
    dropdownSettings?: (Streak.TeamDropdownSettings | null) | undefined;
    /** Allowed tags for a tag field. */
    tagSettings?: (Streak.TeamTagSettings | null) | undefined;
}
