// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Complete option list for a team dropdown field.
 */
export interface TeamDropdownSettingsUpdate {
    /** Dropdown options in display order. */
    items: Streak.TeamDropdownItem[];
}
