// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A Streak team and its membership, sharing, billing, and directory settings.
 */
export interface Team {
    /** Key for this team. */
    key: string;
    /** Timestamp when the team was created, in epoch milliseconds. */
    creationDate: number;
    /** Key for the user who created the team. */
    creator: string;
    /** Members of the team and their team roles. */
    members: Streak.TeamMember[];
    /** Display name for the team. */
    name: string;
    /** Whether sharing outside the team is restricted. */
    sharingRestrictedToTeam?: boolean | undefined;
    /** Whether requests to join the team are approved automatically. */
    automaticallyApproveJoinRequests?: boolean | undefined;
    /** Whether invoice emails are sent automatically for this team. */
    automaticallySendInvoiceEmails?: boolean | undefined;
    /** Additional email addresses that receive team invoices. */
    emailsToSendInvoiceTo: string[];
    /** Key for the user who administers billing for this team. */
    billingAdmin?: (string | null) | undefined;
    /** Timestamp when the team was last persisted, in epoch milliseconds. */
    lastSavedTimestamp: number;
    /** Permissions for the team's system contact and organization lists. */
    contactOrgListPermissions: Record<string, Streak.TeamBasedPermissions>;
    /** Custom contact field definitions for this team. */
    contactSettings: Streak.TeamFieldSettings;
    /** Custom organization field definitions for this team. */
    organizationSettings: Streak.TeamFieldSettings;
}
