// This file was auto-generated by Fern from our API Definition.

/**
 * One tag configured for a team tag field.
 */
export interface TeamTagItem {
    /** Stable key for the tag. */
    key: string;
    /** Display label for the tag. */
    tag: string;
}
