// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Custom field definition in a complete team directory-field replacement.
 */
export interface TeamFieldUpdate {
    /** Display name for the field. */
    name: string;
    /** Stable key for the field. The enclosing map key is used when omitted. */
    key?: (string | null) | undefined;
    /** Data type stored by the field. */
    type: Streak.FieldType;
    /** Default textual field value, when one is configured. */
    defaultValue?: (string | null) | undefined;
    /** Timestamp when the default value last changed, in epoch milliseconds. */
    lastDefaultValueUpdatedTimestamp?: (number | null) | undefined;
    /** Timestamp when the field definition last changed, in epoch milliseconds. */
    lastUpdatedTimestamp?: (number | null) | undefined;
    /** Allowed dropdown options for a dropdown field. */
    dropdownSettings?: (Streak.TeamDropdownSettingsUpdate | null) | undefined;
    /** Allowed tags for a tag field. */
    tagSettings?: (Streak.TeamTagSettingsUpdate | null) | undefined;
}
