// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Complete custom-field replacement for team contacts or organizations.
 */
export interface TeamFieldSettingsUpdate {
    /** Complete custom-field map keyed by stable field key. */
    fields: Record<string, Streak.TeamFieldUpdate>;
}
