// This file was auto-generated by Fern from our API Definition.

/**
 * One explicit user permission in a team list ACL.
 */
export interface TeamAclEntryUpdate {
    /** Key for the user receiving the permission. */
    userKey: string;
    /** Permission set assigned to the user. */
    permissionSetName: string;
}
