// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Complete tag list for a team tag field.
 */
export interface TeamTagSettingsUpdate {
    /** Tags in display order. */
    tags: Streak.TeamTagItem[];
}
