// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Tags configured for a team tag field.
 */
export interface TeamTagSettings {
    /** Tags in display order. */
    tags: Streak.TeamTagItem[];
}
