// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Custom field definitions for a team's contacts or organizations.
 */
export interface TeamFieldSettings {
    /** Custom fields keyed by their stable field key. */
    fields: Record<string, Streak.TeamField>;
}
