// This file was auto-generated by Fern from our API Definition.

/**
 * A user to add when creating a team.
 */
export interface TeamMemberCreate {
    /** Existing user key. Supply either this property or email. */
    userKey?: (string | null) | undefined;
    /** Email address used to find or create the user when userKey is omitted. */
    email?: (string | null) | undefined;
}
