// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * Options configured for a team dropdown field.
 */
export interface TeamDropdownSettings {
    /** Dropdown options in display order. */
    items: Streak.TeamDropdownItem[];
}
