// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A user and their role and invitation state within a team.
 */
export interface TeamMember {
    /** Key for the member's user account. */
    userKey: string;
    /** Role held by the member within the team. */
    role: Streak.Role;
    /** Timestamp when the member was invited, in epoch milliseconds. */
    inviteDate: number;
    /** Current state of the team invitation. */
    inviteStatus: Streak.InviteStatus;
    /** Display name for the member. */
    displayName?: (string | null) | undefined;
    /** Email address for the member. */
    email?: (string | null) | undefined;
    /** Full name for the member. */
    fullName?: (string | null) | undefined;
    /** Given name for the member. */
    givenName?: (string | null) | undefined;
    /** Profile-image URL for the member. */
    image?: (string | null) | undefined;
    /** Type of the member's Streak user account. */
    userType?: (string | null) | undefined;
    /** Level of email-sharing access granted to this team member. */
    emailSharing: Streak.EmailSharing;
}
