// This file was auto-generated by Fern from our API Definition.

export const UserType = {
    Human: "HUMAN",
    Agent: "AGENT",
} as const;
export type UserType = (typeof UserType)[keyof typeof UserType];
