// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

/**
 * A wrapper for a list of User(s) that supports paging when available.
 */
export interface UserListResponse {
    /** Whether there are more User(s) available after this response. */
    hasNextPage?: boolean | undefined;
    /** The User(s) returned by this response. */
    results: Streak.User[];
}
