// This file was auto-generated by Fern from our API Definition.

export interface UserBrief {
    /** Key for this user. */
    userKey: string;
    /** User email address, when available. */
    email?: (string | null) | undefined;
    /** Short display name for this user, when available. */
    displayName?: (string | null) | undefined;
    /** Full display name for this user, when available. */
    fullName?: (string | null) | undefined;
    /** Given name for this user, when available. */
    givenName?: (string | null) | undefined;
    /** Avatar image URL for this user, when available. */
    avatarUrl?: (string | null) | undefined;
}
