// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../index.js";

export interface User {
    /** The user's normalized email address. */
    email: string;
    /** Timestamp when the user account was created, in epoch milliseconds. */
    creationTimestamp: number;
    /** Timestamp when the user entity was last updated, in epoch milliseconds. */
    lastUpdatedTimestamp: number;
    /** Timestamp when the user entity was last persisted, in epoch milliseconds. */
    lastSavedTimestamp: number;
    /** Timestamp when Streak last saw activity for the user, in epoch milliseconds. */
    lastSeenTimestamp?: (number | null) | undefined;
    /** Stable Google profile identifier associated with the user's OAuth account. */
    googleProfileId?: (string | null) | undefined;
    /** URL of the user's Google profile photo, when available. */
    googleProfilePhotoUrl?: (string | null) | undefined;
    /** URL of the user's Google profile, when available. */
    googleProfileLink?: (string | null) | undefined;
    /** Full display name from the user's Google profile. */
    googleProfileFullName?: (string | null) | undefined;
    /** Given name from the user's Google profile, when available. */
    googleProfileFirstName?: (string | null) | undefined;
    /** Family name from the user's Google profile, when available. */
    googleProfileLastName?: (string | null) | undefined;
    /** IANA timezone identifier for the user, such as America/Los_Angeles. */
    timezoneId?: (string | null) | undefined;
    /** Type of Streak user account, such as a human user or an agent user. */
    userType: Streak.UserType;
    /** Whether security report emails are enabled for the user's team pipelines. */
    securityReportOnTeamsPipelines?: boolean | undefined;
    /** Whether external sharing is restricted on the user's team pipelines. */
    externalSharingRestrictionOnTeamsPipelines?: boolean | undefined;
    /** Whether invoice emails should be sent automatically for the user's billing context. */
    automaticallySendInvoiceEmails?: boolean | undefined;
    /** Additional email addresses that should receive invoice emails. */
    emailsToSendInvoiceTo?: (string[] | null) | undefined;
    /** Customer-provided invoice data to include with billing records. */
    customerSpecifiedInvoiceData?: (string | null) | undefined;
    /** Timestamp when the user first completed OAuth, in epoch milliseconds. */
    firstOauthTimestamp?: (number | null) | undefined;
    /** Whether the user wants to receive task digest emails. */
    wantsTaskDigestEmail?: boolean | undefined;
    /** Display name Streak uses for the user in UI surfaces. */
    displayName: string;
    /** Key for this user. */
    key: string;
}
