// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         boxKey: "boxKey",
 *         message: "message"
 *     }
 */
export interface CommentCreateBody {
    boxKey: string;
    /** Comment text. */
    message: string;
    /** Mention ranges in the comment text. */
    mentions?: Streak.CommentMentionBody[] | null;
    /** Parent comment key when creating a reply. */
    parent?: string | null;
    /** Whether to scan the comment text for unstructured @mentions of users display name, first name or email address. */
    searchForAtMentions?: boolean | null;
}
