// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         commentKey: "commentKey"
 *     }
 */
export interface CommentUpdateBody {
    commentKey: string;
    /** New comment text. Omit this field to keep the existing comment text unchanged. */
    message?: string | null;
    /** New mention ranges for the comment text. Omit this field to keep existing mentions unchanged. */
    mentions?: Streak.CommentMentionBody[] | null;
}
