// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         boxKey: "boxKey"
 *     }
 */
export interface GetV2BoxesBoxKeyCommentsRequest {
    boxKey: string;
}
