// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         commentKey: "commentKey"
 *     }
 */
export interface GetV2CommentsCommentKeyRequest {
    commentKey: string;
}
