// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         commentKey: "commentKey",
 *         body: {
 *             emoji: "emoji"
 *         }
 *     }
 */
export interface PostV2CommentsCommentKeyUnreactRequest {
    commentKey: string;
    body: Streak.CommentReactionBody;
}
