// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         organizationKey: "organizationKey"
 *     }
 */
export interface DeleteV2OrganizationsOrganizationKeyRequest {
    /** Key of the organization. */
    organizationKey: string;
}
