// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         teamKey: "teamKey"
 *     }
 */
export interface GetV2TeamsTeamKeyOrganizationsRequest {
    /** Key of the team. */
    teamKey: string;
    /** Cursor returned by the previous response. Omit or leave blank to start from the beginning. */
    cursor?: string;
    /** Maximum number of results to return. Defaults to 100. Values above 1000 are capped. */
    limit?: number;
}
