// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         organizationKey: "organizationKey"
 *     }
 */
export interface OrganizationUpdateBody {
    /** Key of the organization. */
    organizationKey: string;
    /** Replacement organization name. A name or domain must remain after the update. */
    name?: string | null;
    /** Replacement notes. An empty string clears the notes. */
    other?: string | null;
    /** Replacement domains, with the primary domain first. An empty list clears domains if a name remains. */
    domains?: string[] | null;
    /** Replacement industry. */
    industry?: string | null;
    /** Replacement phone numbers. An empty list clears existing phone numbers. */
    phoneNumbers?: string[] | null;
    /** Replacement postal addresses. An empty list clears existing addresses. */
    addresses?: string[] | null;
    /** Replacement company size as text, including employee-count ranges. */
    employeeCount?: string | null;
    /** Replacement organization logo URL. */
    logoURL?: string | null;
    /** Replacement Twitter profile handle or URL. */
    twitterHandle?: string | null;
    /** Replacement Facebook profile handle or URL. */
    facebookHandle?: string | null;
    /** Replacement LinkedIn profile handle or URL. */
    linkedinHandle?: string | null;
    /** Replacement Instagram profile handle or URL. */
    instagramHandle?: string | null;
    /** Replacement contact relationships. An empty list removes existing relationships. */
    contactLinks?: Streak.ContactLinkInput[] | null;
    /** Replacement organization relationships. An empty list removes existing relationships. */
    orgLinks?: Streak.OrganizationLinkInput[] | null;
    /** Custom field values to change, keyed by field ID. Omitted keys and null values are unchanged; an empty object makes no changes. */
    fields?: Record<string, string | null> | null;
}
