// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         teamKey: "teamKey"
 *     }
 */
export interface OrganizationCreateBody {
    /** Key of the team. */
    teamKey: string;
    /** Return an existing organization matching a supplied domain instead of creating another organization. The supplied values are not merged into the existing organization. */
    getIfExisting?: boolean;
    /** Organization name. */
    name?: string | null;
    /** Freeform notes about the organization. */
    other?: string | null;
    /** Website domains for the organization, with the primary domain first. */
    domains?: string[] | null;
    /** Industry of the organization. */
    industry?: string | null;
    /** Phone numbers for the organization. */
    phoneNumbers?: string[] | null;
    /** Postal addresses for the organization. */
    addresses?: string[] | null;
    /** Company size as text, which can include an employee-count range. */
    employeeCount?: string | null;
    /** URL of the organization's logo. */
    logoURL?: string | null;
    /** Twitter profile handle or URL. */
    twitterHandle?: string | null;
    /** Facebook profile handle or URL. */
    facebookHandle?: string | null;
    /** LinkedIn profile handle or URL. */
    linkedinHandle?: string | null;
    /** Instagram profile handle or URL. */
    instagramHandle?: string | null;
}
