// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         teamKey: "teamKey"
 *     }
 */
export interface GetV2TeamsTeamKeyRequest {
    /** Key for the team to return. */
    teamKey: string;
}
