// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         teamKey: "teamKey"
 *     }
 */
export interface TeamUpdateBody {
    /** Key for the team to update. */
    teamKey: string;
    /** New display name for the team. */
    name?: string | null;
    /** Whether sharing outside the team is restricted. */
    sharingRestrictedToTeam?: boolean | null;
    /** Whether requests to join the team are approved automatically. */
    automaticallyApproveJoinRequests?: boolean | null;
    /** Whether invoice emails are sent automatically for this team. */
    automaticallySendInvoiceEmails?: boolean | null;
    /** Complete replacement for additional invoice-recipient email addresses. Omit to leave unchanged; send an empty set to clear. */
    emailsToSendInvoiceTo?: string[] | null;
    /** Complete replacement roster. Omit this property to leave membership unchanged. */
    members?: Streak.TeamMemberUpdate[] | null;
    /** Permission updates keyed by system list. Omitted list entries remain unchanged. */
    contactOrgListPermissions?: Record<string, Streak.TeamBasedPermissionsUpdate | null> | null;
    /** Complete replacement for the team's custom contact fields. Omit to leave unchanged. */
    contactSettings?: Streak.TeamFieldSettingsUpdate | null;
    /** Complete replacement for the team's custom organization fields. Omit to leave unchanged. */
    organizationSettings?: Streak.TeamFieldSettingsUpdate | null;
}
