// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         members: [{}]
 *     }
 */
export interface TeamCreateBody {
    /** Display name for the new team. */
    name: string;
    /** Initial team members. The authenticated creator must be included. */
    members: Streak.TeamMemberCreate[];
}
