// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         teamKey: "teamKey"
 *     }
 */
export interface ContactCreate {
    /** Key of the team. */
    teamKey: string;
    /** Return an existing email match instead of creating a contact. When getIfExisting=true, an email match is returned without merging new values. */
    getIfExisting?: boolean | null;
    /** Given name. */
    givenName?: string | null;
    /** Family name. */
    familyName?: string | null;
    /** Job title. */
    title?: string | null;
    /** Additional notes about the contact. */
    other?: string | null;
    /** Email addresses for the contact. */
    emailAddresses?: string[] | null;
    /** Phone numbers for the contact. */
    phoneNumbers?: string[] | null;
    /** Postal addresses for the contact. */
    addresses?: string[] | null;
    /** Website domains associated with the contact. */
    domains?: string[] | null;
    /** Twitter handle. */
    twitterHandle?: string | null;
    /** Facebook handle. */
    facebookHandle?: string | null;
    /** LinkedIn handle. */
    linkedinHandle?: string | null;
    /** Instagram handle. */
    instagramHandle?: string | null;
    /** URL for the contact's photo. */
    photoUrl?: string | null;
}
