// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         contactKey: "contactKey"
 *     }
 */
export interface ContactUpdate {
    /** Key of the contact. */
    contactKey: string;
    /** New given name; an empty string clears it if another identifier remains. */
    givenName?: string | null;
    /** New family name; an empty string clears it if another identifier remains. */
    familyName?: string | null;
    /** New job title; an empty string clears it. */
    title?: string | null;
    /** New notes; an empty string clears them. */
    other?: string | null;
    /** Replacement email addresses; a contact must retain an email address or a name. */
    emailAddresses?: string[] | null;
    /** Replacement phone numbers. Empty entries are removed. */
    phoneNumbers?: string[] | null;
    /** Replacement postal addresses. Empty entries are removed. */
    addresses?: string[] | null;
    /** Replacement website domains. */
    domains?: string[] | null;
    /** Replacement Twitter handle. */
    twitterHandle?: string | null;
    /** Replacement Facebook handle. */
    facebookHandle?: string | null;
    /** Replacement LinkedIn handle. */
    linkedinHandle?: string | null;
    /** Replacement Instagram handle. */
    instagramHandle?: string | null;
    /** Replacement photo URL. */
    photoUrl?: string | null;
    /** Custom-field values to merge by field key. Null entries are ignored; an empty map leaves existing fields unchanged. */
    fields?: Record<string, string | null> | null;
    /** Replacement links to contacts; an empty list removes the links. */
    contactLinks?: Streak.ContactLinkInput[] | null;
    /** Replacement links to organizations; an empty list removes the links. */
    orgLinks?: Streak.OrganizationLinkInput[] | null;
}
