// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contactKey: "contactKey"
 *     }
 */
export interface DeleteV2ContactsContactKeyRequest {
    /** Key of the contact. */
    contactKey: string;
}
