// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         teamKey: "teamKey",
 *         after: 1646870400
 *     }
 */
export interface GetV2TeamsTeamKeyContactsRequest {
    /** Key of the team. */
    teamKey: string;
    /** Include contacts last saved at or after this epoch-seconds timestamp. */
    after?: number;
    /** Cursor returned by the previous response. Omit or leave blank to start from the beginning. */
    cursor?: string;
    /** Maximum number of results to return. Defaults to 100. Values above 1000 are capped. */
    limit?: number;
}
