// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetV1SearchRequest {
    /** Exact box name to search for. */
    name?: string | null;
    /** Zero-based page number. */
    page?: number;
    /** Pipeline keys to constrain the search to. */
    pipelineKey?: string[] | null;
    /** Full-text query to search across boxes, contacts, and organizations. */
    query?: string | null;
    /** Stage keys to constrain the search to. */
    stageKey?: string[] | null;
    /** Team keys to constrain the search to. */
    teamKey?: string[] | null;
}
