// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ApiKeysClient", () => {
    test("listApiKeys", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = [
            {
                apiKey: "apiKey",
                key: "key",
                creationTimestamp: 1646870400000,
                lastSavedTimestamp: 1646870400000,
                keyType: "USER",
                teamKey: "teamKey",
            },
        ];

        server.mockEndpoint().get("/v1/apikeys").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKeys.listApiKeys();
        expect(response).toEqual(rawResponseBody);
    });

    test("createApiKey", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            apiKey: "apiKey",
            key: "key",
            creationTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            keyType: "USER",
            teamKey: "teamKey",
        };

        server.mockEndpoint().put("/v1/apikeys").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKeys.createApiKey();
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteApiKey", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v1/apikeys/apiKeyKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.deleteApiKey({
            apiKeyKey: "apiKeyKey",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
