// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CommentsClient", () => {
    test("listComments", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            hasNextPage: true,
            results: [
                {
                    key: "key",
                    boxKey: "boxKey",
                    pipelineKey: "pipelineKey",
                    creatorKey: "creatorKey",
                    newsfeedEntryKey: "newsfeedEntryKey",
                    timestamp: 1646870400000,
                    message: "message",
                    mentions: [{ userKey: "userKey" }],
                    parent: "parent",
                    children: ["children"],
                    reactionSummary: [{ emoji: "emoji", users: [{ userKey: "userKey" }] }],
                    lastSavedTimestamp: 1646870400000,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/boxes/boxKey/comments")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.listComments({
            boxKey: "boxKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createComment", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { message: "message" };
        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            newsfeedEntryKey: "newsfeedEntryKey",
            timestamp: 1646870400000,
            message: "message",
            mentions: [{ userKey: "userKey", offset: 1, length: 1 }],
            parent: "parent",
            children: ["children"],
            reactionSummary: [{ emoji: "emoji", count: 1, users: [{ userKey: "userKey" }] }],
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .post("/v2/boxes/boxKey/comments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.createComment({
            boxKey: "boxKey",
            message: "message",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getComment", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            newsfeedEntryKey: "newsfeedEntryKey",
            timestamp: 1646870400000,
            message: "message",
            mentions: [{ userKey: "userKey", offset: 1, length: 1 }],
            parent: "parent",
            children: ["children"],
            reactionSummary: [{ emoji: "emoji", count: 1, users: [{ userKey: "userKey" }] }],
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .get("/v2/comments/commentKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.getComment({
            commentKey: "commentKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateComment", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            newsfeedEntryKey: "newsfeedEntryKey",
            timestamp: 1646870400000,
            message: "message",
            mentions: [{ userKey: "userKey", offset: 1, length: 1 }],
            parent: "parent",
            children: ["children"],
            reactionSummary: [{ emoji: "emoji", count: 1, users: [{ userKey: "userKey" }] }],
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .post("/v2/comments/commentKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.updateComment({
            commentKey: "commentKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteComment", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v2/comments/commentKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.deleteComment({
            commentKey: "commentKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("reactToComment", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { emoji: "emoji" };
        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            newsfeedEntryKey: "newsfeedEntryKey",
            timestamp: 1646870400000,
            message: "message",
            mentions: [{ userKey: "userKey", offset: 1, length: 1 }],
            parent: "parent",
            children: ["children"],
            reactionSummary: [{ emoji: "emoji", count: 1, users: [{ userKey: "userKey" }] }],
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .post("/v2/comments/commentKey/react")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.reactToComment({
            commentKey: "commentKey",
            body: {
                emoji: "emoji",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeCommentReaction", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { emoji: "emoji" };
        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            newsfeedEntryKey: "newsfeedEntryKey",
            timestamp: 1646870400000,
            message: "message",
            mentions: [{ userKey: "userKey", offset: 1, length: 1 }],
            parent: "parent",
            children: ["children"],
            reactionSummary: [{ emoji: "emoji", count: 1, users: [{ userKey: "userKey" }] }],
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .post("/v2/comments/commentKey/unreact")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.comments.removeCommentReaction({
            commentKey: "commentKey",
            body: {
                emoji: "emoji",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });
});
