// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ContactClient", () => {
    test("getContactsInBulk", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = ["string"];
        const rawResponseBody = {
            key: {
                key: "key",
                teamKey: "teamKey",
                givenName: "givenName",
                familyName: "familyName",
                other: "other",
                title: "title",
                emailAddresses: ["emailAddresses"],
                phoneNumbers: ["phoneNumbers"],
                addresses: ["addresses"],
                domains: ["domains"],
                normalizedDomains: ["normalizedDomains"],
                twitterHandle: "twitterHandle",
                facebookHandle: "facebookHandle",
                linkedinHandle: "linkedinHandle",
                instagramHandle: "instagramHandle",
                photoUrl: "photoUrl",
                lastSavedUserKey: "lastSavedUserKey",
                creatorKey: "creatorKey",
                creationDate: 1646870400000,
                versionTimestamp: 1646870400000,
                lastSavedTimestamp: 1646870400000,
                lastEnrichmentTimestamp: 1646870400000,
                contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                fields: { key: "value" },
            },
        };

        server
            .mockEndpoint()
            .post("/v2/contacts/batch/get")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contact.getContactsInBulk(["string"]);
        expect(response).toEqual(rawResponseBody);
    });

    test("getContact", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            teamKey: "teamKey",
            givenName: "givenName",
            familyName: "familyName",
            other: "other",
            title: "title",
            emailAddresses: ["emailAddresses"],
            phoneNumbers: ["phoneNumbers"],
            addresses: ["addresses"],
            domains: ["domains"],
            normalizedDomains: ["normalizedDomains"],
            twitterHandle: "twitterHandle",
            facebookHandle: "facebookHandle",
            linkedinHandle: "linkedinHandle",
            instagramHandle: "instagramHandle",
            photoUrl: "photoUrl",
            lastSavedUserKey: "lastSavedUserKey",
            creatorKey: "creatorKey",
            creationDate: 1646870400000,
            versionTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastEnrichmentTimestamp: 1646870400000,
            contactLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            orgLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            fields: { key: "value" },
        };

        server
            .mockEndpoint()
            .get("/v2/contacts/contactKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contact.getContact({
            contactKey: "contactKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateContact", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            teamKey: "teamKey",
            givenName: "givenName",
            familyName: "familyName",
            other: "other",
            title: "title",
            emailAddresses: ["emailAddresses"],
            phoneNumbers: ["phoneNumbers"],
            addresses: ["addresses"],
            domains: ["domains"],
            normalizedDomains: ["normalizedDomains"],
            twitterHandle: "twitterHandle",
            facebookHandle: "facebookHandle",
            linkedinHandle: "linkedinHandle",
            instagramHandle: "instagramHandle",
            photoUrl: "photoUrl",
            lastSavedUserKey: "lastSavedUserKey",
            creatorKey: "creatorKey",
            creationDate: 1646870400000,
            versionTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastEnrichmentTimestamp: 1646870400000,
            contactLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            orgLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            fields: { key: "value" },
        };

        server
            .mockEndpoint()
            .post("/v2/contacts/contactKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contact.updateContact({
            contactKey: "contactKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteContact", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v2/contacts/contactKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contact.deleteContact({
            contactKey: "contactKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listContacts", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            results: [
                {
                    key: "key",
                    teamKey: "teamKey",
                    givenName: "givenName",
                    familyName: "familyName",
                    other: "other",
                    title: "title",
                    emailAddresses: ["emailAddresses"],
                    phoneNumbers: ["phoneNumbers"],
                    addresses: ["addresses"],
                    domains: ["domains"],
                    normalizedDomains: ["normalizedDomains"],
                    twitterHandle: "twitterHandle",
                    facebookHandle: "facebookHandle",
                    linkedinHandle: "linkedinHandle",
                    instagramHandle: "instagramHandle",
                    photoUrl: "photoUrl",
                    lastSavedUserKey: "lastSavedUserKey",
                    creatorKey: "creatorKey",
                    creationDate: 1646870400000,
                    versionTimestamp: 1646870400000,
                    lastSavedTimestamp: 1646870400000,
                    lastEnrichmentTimestamp: 1646870400000,
                    contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                    orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                    fields: { key: "value" },
                },
            ],
            cursor: "cursor",
        };

        server
            .mockEndpoint()
            .get("/v2/teams/teamKey/contacts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contact.listContacts({
            teamKey: "teamKey",
            after: 1646870400,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createContact", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            teamKey: "teamKey",
            givenName: "givenName",
            familyName: "familyName",
            other: "other",
            title: "title",
            emailAddresses: ["emailAddresses"],
            phoneNumbers: ["phoneNumbers"],
            addresses: ["addresses"],
            domains: ["domains"],
            normalizedDomains: ["normalizedDomains"],
            twitterHandle: "twitterHandle",
            facebookHandle: "facebookHandle",
            linkedinHandle: "linkedinHandle",
            instagramHandle: "instagramHandle",
            photoUrl: "photoUrl",
            lastSavedUserKey: "lastSavedUserKey",
            creatorKey: "creatorKey",
            creationDate: 1646870400000,
            versionTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastEnrichmentTimestamp: 1646870400000,
            contactLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            orgLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            fields: { key: "value" },
        };

        server
            .mockEndpoint()
            .post("/v2/teams/teamKey/contacts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contact.createContact({
            teamKey: "teamKey",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
