// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MeetingsClient", () => {
    test("listMeetings", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            hasNextPage: true,
            results: [
                {
                    key: "key",
                    boxKey: "boxKey",
                    pipelineKey: "pipelineKey",
                    creatorKey: "creatorKey",
                    isDraft: true,
                    taskKeys: ["taskKeys"],
                    creationDate: 1646870400000,
                    meetingType: "CALL_LOG",
                    startTimestamp: 1646870400000,
                    duration: 1000000,
                    notes: "notes",
                    lastSavedTimestamp: 1646870400000,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/boxes/boxKey/meetings")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.meetings.listMeetings({
            boxKey: "boxKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createMeeting", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { meetingType: "CALL_LOG", startTimestamp: 1646870400000 };
        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            isDraft: true,
            taskKeys: ["taskKeys"],
            creationDate: 1646870400000,
            meetingType: "CALL_LOG",
            startTimestamp: 1646870400000,
            duration: 1000000,
            notes: "notes",
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .post("/v2/boxes/boxKey/meetings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.meetings.createMeeting({
            boxKey: "boxKey",
            meetingType: "CALL_LOG",
            startTimestamp: 1646870400000,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getMeeting", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            isDraft: true,
            taskKeys: ["taskKeys"],
            creationDate: 1646870400000,
            meetingType: "CALL_LOG",
            startTimestamp: 1646870400000,
            duration: 1000000,
            notes: "notes",
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .get("/v2/meetings/meetingKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.meetings.getMeeting({
            meetingKey: "meetingKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateMeeting", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            isDraft: true,
            taskKeys: ["taskKeys"],
            creationDate: 1646870400000,
            meetingType: "CALL_LOG",
            startTimestamp: 1646870400000,
            duration: 1000000,
            notes: "notes",
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .post("/v2/meetings/meetingKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.meetings.updateMeeting({
            meetingKey: "meetingKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteMeeting", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v2/meetings/meetingKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.meetings.deleteMeeting({
            meetingKey: "meetingKey",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
