// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("OrganizationClient", () => {
    test("getOrganizationsInABatch", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = ["string"];
        const rawResponseBody = {
            key: {
                key: "key",
                teamKey: "teamKey",
                name: "name",
                other: "other",
                domains: ["domains"],
                normalizedDomains: ["normalizedDomains"],
                industry: "industry",
                phoneNumbers: ["phoneNumbers"],
                addresses: ["addresses"],
                employeeCount: "employeeCount",
                logoURL: "logoURL",
                twitterHandle: "twitterHandle",
                facebookHandle: "facebookHandle",
                linkedinHandle: "linkedinHandle",
                instagramHandle: "instagramHandle",
                lastSavedUserKey: "lastSavedUserKey",
                creatorKey: "creatorKey",
                creationDate: 1646870400000,
                versionTimestamp: 1646870400000,
                lastSavedTimestamp: 1646870400000,
                lastEnrichmentTimestamp: 1646870400000,
                contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                fields: { key: "value" },
            },
        };

        server
            .mockEndpoint()
            .post("/v2/organizations/batch/get")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.getOrganizationsInABatch(["string"]);
        expect(response).toEqual(rawResponseBody);
    });

    test("getAnOrganization", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            teamKey: "teamKey",
            name: "name",
            other: "other",
            domains: ["domains"],
            normalizedDomains: ["normalizedDomains"],
            industry: "industry",
            phoneNumbers: ["phoneNumbers"],
            addresses: ["addresses"],
            employeeCount: "employeeCount",
            logoURL: "logoURL",
            twitterHandle: "twitterHandle",
            facebookHandle: "facebookHandle",
            linkedinHandle: "linkedinHandle",
            instagramHandle: "instagramHandle",
            lastSavedUserKey: "lastSavedUserKey",
            creatorKey: "creatorKey",
            creationDate: 1646870400000,
            versionTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastEnrichmentTimestamp: 1646870400000,
            contactLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            orgLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            fields: { key: "value" },
        };

        server
            .mockEndpoint()
            .get("/v2/organizations/organizationKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.getAnOrganization({
            organizationKey: "organizationKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAnOrganization", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            teamKey: "teamKey",
            name: "name",
            other: "other",
            domains: ["domains"],
            normalizedDomains: ["normalizedDomains"],
            industry: "industry",
            phoneNumbers: ["phoneNumbers"],
            addresses: ["addresses"],
            employeeCount: "employeeCount",
            logoURL: "logoURL",
            twitterHandle: "twitterHandle",
            facebookHandle: "facebookHandle",
            linkedinHandle: "linkedinHandle",
            instagramHandle: "instagramHandle",
            lastSavedUserKey: "lastSavedUserKey",
            creatorKey: "creatorKey",
            creationDate: 1646870400000,
            versionTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastEnrichmentTimestamp: 1646870400000,
            contactLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            orgLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            fields: { key: "value" },
        };

        server
            .mockEndpoint()
            .post("/v2/organizations/organizationKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.updateAnOrganization({
            organizationKey: "organizationKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteAnOrganization", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v2/organizations/organizationKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.deleteAnOrganization({
            organizationKey: "organizationKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listOrganizations", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            results: [
                {
                    key: "key",
                    teamKey: "teamKey",
                    name: "name",
                    other: "other",
                    domains: ["domains"],
                    normalizedDomains: ["normalizedDomains"],
                    industry: "industry",
                    phoneNumbers: ["phoneNumbers"],
                    addresses: ["addresses"],
                    employeeCount: "employeeCount",
                    logoURL: "logoURL",
                    twitterHandle: "twitterHandle",
                    facebookHandle: "facebookHandle",
                    linkedinHandle: "linkedinHandle",
                    instagramHandle: "instagramHandle",
                    lastSavedUserKey: "lastSavedUserKey",
                    creatorKey: "creatorKey",
                    creationDate: 1646870400000,
                    versionTimestamp: 1646870400000,
                    lastSavedTimestamp: 1646870400000,
                    lastEnrichmentTimestamp: 1646870400000,
                    contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                    orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                    fields: { key: "value" },
                },
            ],
            cursor: "cursor",
        };

        server
            .mockEndpoint()
            .get("/v2/teams/teamKey/organizations")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.listOrganizations({
            teamKey: "teamKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAnOrganization", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            teamKey: "teamKey",
            name: "name",
            other: "other",
            domains: ["domains"],
            normalizedDomains: ["normalizedDomains"],
            industry: "industry",
            phoneNumbers: ["phoneNumbers"],
            addresses: ["addresses"],
            employeeCount: "employeeCount",
            logoURL: "logoURL",
            twitterHandle: "twitterHandle",
            facebookHandle: "facebookHandle",
            linkedinHandle: "linkedinHandle",
            instagramHandle: "instagramHandle",
            lastSavedUserKey: "lastSavedUserKey",
            creatorKey: "creatorKey",
            creationDate: 1646870400000,
            versionTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastEnrichmentTimestamp: 1646870400000,
            contactLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            orgLinks: [{ key: "key", isMagicLinked: true, creationTimestamp: 1646870400000 }],
            fields: { key: "value" },
        };

        server
            .mockEndpoint()
            .post("/v2/teams/teamKey/organizations")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organization.createAnOrganization({
            teamKey: "teamKey",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
