// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PipelineStageClient", () => {
    test("listStages", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            key: {
                key: "key",
                name: "name",
                color: { foregroundColor: "foregroundColor", backgroundColor: "backgroundColor" },
                isColorFromTheme: true,
                boxCount: 1,
            },
        };

        server
            .mockEndpoint()
            .get("/v2/pipelines/pipelineKey/stages")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipelineStage.listStages({
            pipelineKey: "pipelineKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createStage", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            key: "key",
            name: "name",
            color: { foregroundColor: "foregroundColor", backgroundColor: "backgroundColor" },
            isColorFromTheme: true,
            boxCount: 1,
        };

        server
            .mockEndpoint()
            .post("/v2/pipelines/pipelineKey/stages")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipelineStage.createStage({
            pipelineKey: "pipelineKey",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getStage", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            name: "name",
            color: { foregroundColor: "foregroundColor", backgroundColor: "backgroundColor" },
            isColorFromTheme: true,
            boxCount: 1,
        };

        server
            .mockEndpoint()
            .get("/v2/pipelines/pipelineKey/stages/stageKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipelineStage.getStage({
            pipelineKey: "pipelineKey",
            stageKey: "stageKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateStage", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            name: "name",
            color: { foregroundColor: "foregroundColor", backgroundColor: "backgroundColor" },
            isColorFromTheme: true,
            boxCount: 1,
        };

        server
            .mockEndpoint()
            .post("/v2/pipelines/pipelineKey/stages/stageKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipelineStage.updateStage({
            pipelineKey: "pipelineKey",
            stageKey: "stageKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteStage", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v2/pipelines/pipelineKey/stages/stageKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipelineStage.deleteStage({
            pipelineKey: "pipelineKey",
            stageKey: "stageKey",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
