// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PipelineClient", () => {
    test("listPipelineFields", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                key: "key",
                name: "name",
                type: "TEXT_INPUT",
                defaultValue: { key: "value" },
                lastDefaultValueUpdatedTimestamp: 1646870400000,
                lastUpdatedTimestamp: 1646870400000,
                dropdownSettings: { items: [{ name: "name" }] },
                tagSettings: { tags: [{ key: "key", tag: "tag" }] },
                aiSettings: { prompt: "prompt", source: "BOX_TIMELINE" },
            },
        ];

        server
            .mockEndpoint()
            .get("/v1/pipelines/pipelineKey/fields")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.listPipelineFields({
            pipelineKey: "pipelineKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPipelineField", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            name: "name",
            type: "TEXT_INPUT",
            defaultValue: { key: "value" },
            lastDefaultValueUpdatedTimestamp: 1646870400000,
            lastUpdatedTimestamp: 1646870400000,
            dropdownSettings: { items: [{ name: "name" }] },
            tagSettings: { tags: [{ key: "key", tag: "tag" }] },
            aiSettings: { prompt: "prompt", source: "BOX_TIMELINE" },
        };

        server
            .mockEndpoint()
            .get("/v1/pipelines/pipelineKey/fields/fieldKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.getPipelineField({
            pipelineKey: "pipelineKey",
            fieldKey: "fieldKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updatePipelineField", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            name: "name",
            type: "TEXT_INPUT",
            defaultValue: { key: "value" },
            lastDefaultValueUpdatedTimestamp: 1646870400000,
            lastUpdatedTimestamp: 1646870400000,
            dropdownSettings: { items: [{ name: "name" }] },
            tagSettings: { tags: [{ key: "key", tag: "tag" }] },
            aiSettings: { prompt: "prompt", source: "BOX_TIMELINE" },
        };

        server
            .mockEndpoint()
            .post("/v1/pipelines/pipelineKey/fields/fieldKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.updatePipelineField({
            pipelineKey: "pipelineKey",
            fieldKey: "fieldKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deletePipelineField", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v1/pipelines/pipelineKey/fields/fieldKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.deletePipelineField({
            pipelineKey: "pipelineKey",
            fieldKey: "fieldKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listPipelines", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hasNextPage: true,
            results: [
                {
                    key: "key",
                    teamKey: "teamKey",
                    creatorKey: "creatorKey",
                    name: "name",
                    icon: "icon",
                    description: "description",
                    sharingRestrictedToTeam: true,
                    fields: [
                        {
                            key: "key",
                            name: "name",
                            type: "TEXT_INPUT",
                            lastDefaultValueUpdatedTimestamp: 1646870400000,
                            lastUpdatedTimestamp: 1646870400000,
                            aiSettings: { prompt: "prompt", source: "BOX_TIMELINE" },
                        },
                    ],
                    stages: {
                        key: {
                            key: "key",
                            name: "name",
                            color: { foregroundColor: "foregroundColor", backgroundColor: "backgroundColor" },
                        },
                    },
                    stageOrder: ["stageOrder"],
                    stageColorTheme: "DEFAULT",
                    creationTimestamp: 1646870400000,
                    lastUpdatedTimestamp: 1646870400000,
                    formulasLastUpdatedTimestamp: 1646870400000,
                    customPermissionSets: {
                        key: { permissions: [{ entityType: "entityType", action: "GET", conditionalCheck: "NONE" }] },
                    },
                    defaultPermissionSetName: "defaultPermissionSetName",
                    aclEntries: [{ userKey: "userKey", permissionSetName: "permissionSetName" }],
                    creationSourceType: "HUMAN",
                    boxCount: 1,
                    lastSavedTimestamp: 1646870400000,
                },
            ],
        };

        server.mockEndpoint().get("/v2/pipelines").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.pipeline.listPipelines();
        expect(response).toEqual(rawResponseBody);
    });

    test("createPipeline", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", teamKey: "teamKey", stages: ["stages"] };

        server.mockEndpoint().post("/v2/pipelines").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.pipeline.createPipeline({
            name: "name",
            teamKey: "teamKey",
            stages: ["stages"],
        });
        expect(response).toEqual(undefined);
    });

    test("getPipeline", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            teamKey: "teamKey",
            creatorKey: "creatorKey",
            name: "name",
            icon: "icon",
            description: "description",
            sharingRestrictedToTeam: true,
            fields: [
                {
                    key: "key",
                    name: "name",
                    type: "TEXT_INPUT",
                    defaultValue: { key: "value" },
                    lastDefaultValueUpdatedTimestamp: 1646870400000,
                    lastUpdatedTimestamp: 1646870400000,
                    dropdownSettings: { items: [{ name: "name" }] },
                    tagSettings: { tags: [{ key: "key", tag: "tag" }] },
                    aiSettings: { prompt: "prompt", source: "BOX_TIMELINE" },
                },
            ],
            stages: {
                key: {
                    key: "key",
                    name: "name",
                    color: { foregroundColor: "foregroundColor", backgroundColor: "backgroundColor" },
                    isColorFromTheme: true,
                    boxCount: 1,
                },
            },
            stageOrder: ["stageOrder"],
            stageColorTheme: "DEFAULT",
            creationTimestamp: 1646870400000,
            lastUpdatedTimestamp: 1646870400000,
            formulasLastUpdatedTimestamp: 1646870400000,
            customPermissionSets: {
                key: {
                    permissions: [{ entityType: "entityType", action: "GET", conditionalCheck: "NONE" }],
                    userAssignable: true,
                },
            },
            defaultPermissionSetName: "defaultPermissionSetName",
            aclEntries: [
                {
                    userKey: "userKey",
                    permissionSetName: "permissionSetName",
                    email: "email",
                    displayName: "displayName",
                    fullName: "fullName",
                    givenName: "givenName",
                    image: "image",
                    userType: "userType",
                    isReadOnly: true,
                },
            ],
            creationSourceType: "HUMAN",
            boxCount: 1,
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .get("/v2/pipelines/pipelineKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.getPipeline({
            pipelineKey: "pipelineKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updatePipeline", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            teamKey: "teamKey",
            creatorKey: "creatorKey",
            name: "name",
            icon: "icon",
            description: "description",
            sharingRestrictedToTeam: true,
            fields: [
                {
                    key: "key",
                    name: "name",
                    type: "TEXT_INPUT",
                    defaultValue: { key: "value" },
                    lastDefaultValueUpdatedTimestamp: 1646870400000,
                    lastUpdatedTimestamp: 1646870400000,
                    dropdownSettings: { items: [{ name: "name" }] },
                    tagSettings: { tags: [{ key: "key", tag: "tag" }] },
                    aiSettings: { prompt: "prompt", source: "BOX_TIMELINE" },
                },
            ],
            stages: {
                key: {
                    key: "key",
                    name: "name",
                    color: { foregroundColor: "foregroundColor", backgroundColor: "backgroundColor" },
                    isColorFromTheme: true,
                    boxCount: 1,
                },
            },
            stageOrder: ["stageOrder"],
            stageColorTheme: "DEFAULT",
            creationTimestamp: 1646870400000,
            lastUpdatedTimestamp: 1646870400000,
            formulasLastUpdatedTimestamp: 1646870400000,
            customPermissionSets: {
                key: {
                    permissions: [{ entityType: "entityType", action: "GET", conditionalCheck: "NONE" }],
                    userAssignable: true,
                },
            },
            defaultPermissionSetName: "defaultPermissionSetName",
            aclEntries: [
                {
                    userKey: "userKey",
                    permissionSetName: "permissionSetName",
                    email: "email",
                    displayName: "displayName",
                    fullName: "fullName",
                    givenName: "givenName",
                    image: "image",
                    userType: "userType",
                    isReadOnly: true,
                },
            ],
            creationSourceType: "HUMAN",
            boxCount: 1,
            lastSavedTimestamp: 1646870400000,
        };

        server
            .mockEndpoint()
            .post("/v2/pipelines/pipelineKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.updatePipeline({
            pipelineKey: "pipelineKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deletePipeline", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v2/pipelines/pipelineKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.deletePipeline({
            pipelineKey: "pipelineKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createPipelineField", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", type: "TEXT_INPUT" };
        const rawResponseBody = {
            key: "key",
            name: "name",
            type: "TEXT_INPUT",
            defaultValue: { key: "value" },
            lastDefaultValueUpdatedTimestamp: 1646870400000,
            lastUpdatedTimestamp: 1646870400000,
            dropdownSettings: { items: [{ name: "name" }] },
            tagSettings: { tags: [{ key: "key", tag: "tag" }] },
            aiSettings: { prompt: "prompt", source: "BOX_TIMELINE" },
        };

        server
            .mockEndpoint()
            .post("/v2/pipelines/pipelineKey/fields")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.createPipelineField({
            pipelineKey: "pipelineKey",
            body: {
                name: "name",
                type: "TEXT_INPUT",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });
});
