// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SearchClient", () => {
    test("searchBoxesContactsAndOrganizations", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            results: { boxes: [{ boxKey: "boxKey" }], contacts: [{}], orgs: [{}] },
            query: "query",
            page: 1,
        };

        server.mockEndpoint().get("/v1/search").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.search.searchBoxesContactsAndOrganizations();
        expect(response).toEqual(rawResponseBody);
    });
});
