// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TasksClient", () => {
    test("listBoxTasks", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            hasNextPage: true,
            results: [
                {
                    key: "key",
                    boxKey: "boxKey",
                    pipelineKey: "pipelineKey",
                    creatorKey: "creatorKey",
                    creator: { userKey: "userKey" },
                    assignedTo: [{ userKey: "userKey" }],
                    creationDate: 1646870400000,
                    lastSavedTimestamp: 1646870400000,
                    lastStatusChangeDate: 1646870400000,
                    dueDate: 1646870400000,
                    text: "text",
                    actions: [
                        {
                            type: "EMAIL",
                            value: "value",
                            contact: {
                                key: "key",
                                teamKey: "teamKey",
                                emailAddresses: ["emailAddresses"],
                                phoneNumbers: ["phoneNumbers"],
                                addresses: ["addresses"],
                                domains: ["domains"],
                                normalizedDomains: ["normalizedDomains"],
                                creationDate: 1646870400000,
                                versionTimestamp: 1646870400000,
                                lastSavedTimestamp: 1646870400000,
                                lastEnrichmentTimestamp: 1646870400000,
                                contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                                orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                                fields: { key: "value" },
                            },
                        },
                    ],
                    status: "NOT_DONE",
                    reminderStatus: "NONE",
                    meetingKey: "meetingKey",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/boxes/boxKey/tasks")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tasks.listBoxTasks({
            boxKey: "boxKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createTask", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { text: "text" };
        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            creator: {
                userKey: "userKey",
                email: "email",
                displayName: "displayName",
                fullName: "fullName",
                givenName: "givenName",
                avatarUrl: "avatarUrl",
            },
            assignedTo: [
                {
                    userKey: "userKey",
                    email: "email",
                    displayName: "displayName",
                    fullName: "fullName",
                    givenName: "givenName",
                    avatarUrl: "avatarUrl",
                },
            ],
            creationDate: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastStatusChangeDate: 1646870400000,
            dueDate: 1646870400000,
            text: "text",
            actions: [
                {
                    type: "EMAIL",
                    value: "value",
                    contact: {
                        key: "key",
                        teamKey: "teamKey",
                        emailAddresses: ["emailAddresses"],
                        phoneNumbers: ["phoneNumbers"],
                        addresses: ["addresses"],
                        domains: ["domains"],
                        normalizedDomains: ["normalizedDomains"],
                        creationDate: 1646870400000,
                        versionTimestamp: 1646870400000,
                        lastSavedTimestamp: 1646870400000,
                        lastEnrichmentTimestamp: 1646870400000,
                        contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                        orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                        fields: { key: "value" },
                    },
                },
            ],
            status: "NOT_DONE",
            reminderStatus: "NONE",
            meetingKey: "meetingKey",
        };

        server
            .mockEndpoint()
            .post("/v2/boxes/boxKey/tasks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tasks.createTask({
            boxKey: "boxKey",
            text: "text",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listUpcomingTasks", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            hasNextPage: true,
            results: [
                {
                    key: "key",
                    boxKey: "boxKey",
                    pipelineKey: "pipelineKey",
                    creatorKey: "creatorKey",
                    creator: { userKey: "userKey" },
                    assignedTo: [{ userKey: "userKey" }],
                    creationDate: 1646870400000,
                    lastSavedTimestamp: 1646870400000,
                    lastStatusChangeDate: 1646870400000,
                    dueDate: 1646870400000,
                    text: "text",
                    actions: [
                        {
                            type: "EMAIL",
                            value: "value",
                            contact: {
                                key: "key",
                                teamKey: "teamKey",
                                emailAddresses: ["emailAddresses"],
                                phoneNumbers: ["phoneNumbers"],
                                addresses: ["addresses"],
                                domains: ["domains"],
                                normalizedDomains: ["normalizedDomains"],
                                creationDate: 1646870400000,
                                versionTimestamp: 1646870400000,
                                lastSavedTimestamp: 1646870400000,
                                lastEnrichmentTimestamp: 1646870400000,
                                contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                                orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                                fields: { key: "value" },
                            },
                        },
                    ],
                    status: "NOT_DONE",
                    reminderStatus: "NONE",
                    meetingKey: "meetingKey",
                },
            ],
        };

        server.mockEndpoint().get("/v2/tasks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tasks.listUpcomingTasks();
        expect(response).toEqual(rawResponseBody);
    });

    test("getTask", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            creator: {
                userKey: "userKey",
                email: "email",
                displayName: "displayName",
                fullName: "fullName",
                givenName: "givenName",
                avatarUrl: "avatarUrl",
            },
            assignedTo: [
                {
                    userKey: "userKey",
                    email: "email",
                    displayName: "displayName",
                    fullName: "fullName",
                    givenName: "givenName",
                    avatarUrl: "avatarUrl",
                },
            ],
            creationDate: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastStatusChangeDate: 1646870400000,
            dueDate: 1646870400000,
            text: "text",
            actions: [
                {
                    type: "EMAIL",
                    value: "value",
                    contact: {
                        key: "key",
                        teamKey: "teamKey",
                        emailAddresses: ["emailAddresses"],
                        phoneNumbers: ["phoneNumbers"],
                        addresses: ["addresses"],
                        domains: ["domains"],
                        normalizedDomains: ["normalizedDomains"],
                        creationDate: 1646870400000,
                        versionTimestamp: 1646870400000,
                        lastSavedTimestamp: 1646870400000,
                        lastEnrichmentTimestamp: 1646870400000,
                        contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                        orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                        fields: { key: "value" },
                    },
                },
            ],
            status: "NOT_DONE",
            reminderStatus: "NONE",
            meetingKey: "meetingKey",
        };

        server.mockEndpoint().get("/v2/tasks/taskKey").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tasks.getTask({
            taskKey: "taskKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateTask", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            boxKey: "boxKey",
            pipelineKey: "pipelineKey",
            creatorKey: "creatorKey",
            creator: {
                userKey: "userKey",
                email: "email",
                displayName: "displayName",
                fullName: "fullName",
                givenName: "givenName",
                avatarUrl: "avatarUrl",
            },
            assignedTo: [
                {
                    userKey: "userKey",
                    email: "email",
                    displayName: "displayName",
                    fullName: "fullName",
                    givenName: "givenName",
                    avatarUrl: "avatarUrl",
                },
            ],
            creationDate: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastStatusChangeDate: 1646870400000,
            dueDate: 1646870400000,
            text: "text",
            actions: [
                {
                    type: "EMAIL",
                    value: "value",
                    contact: {
                        key: "key",
                        teamKey: "teamKey",
                        emailAddresses: ["emailAddresses"],
                        phoneNumbers: ["phoneNumbers"],
                        addresses: ["addresses"],
                        domains: ["domains"],
                        normalizedDomains: ["normalizedDomains"],
                        creationDate: 1646870400000,
                        versionTimestamp: 1646870400000,
                        lastSavedTimestamp: 1646870400000,
                        lastEnrichmentTimestamp: 1646870400000,
                        contactLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                        orgLinks: [{ key: "key", creationTimestamp: 1646870400000 }],
                        fields: { key: "value" },
                    },
                },
            ],
            status: "NOT_DONE",
            reminderStatus: "NONE",
            meetingKey: "meetingKey",
        };

        server
            .mockEndpoint()
            .post("/v2/tasks/taskKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tasks.updateTask({
            taskKey: "taskKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteTask", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "message" };

        server
            .mockEndpoint()
            .delete("/v2/tasks/taskKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tasks.deleteTask({
            taskKey: "taskKey",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
