// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TeamClient", () => {
    test("createTeam", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { name: "name", members: [{}] };
        const rawResponseBody = {
            key: "key",
            creationDate: 1646870400000,
            creator: "creator",
            members: [
                {
                    userKey: "userKey",
                    role: "Member",
                    inviteDate: 1646870400000,
                    inviteStatus: "Pending",
                    displayName: "displayName",
                    email: "email",
                    fullName: "fullName",
                    givenName: "givenName",
                    image: "image",
                    userType: "userType",
                    emailSharing: "None",
                },
            ],
            name: "name",
            sharingRestrictedToTeam: true,
            automaticallyApproveJoinRequests: true,
            automaticallySendInvoiceEmails: true,
            emailsToSendInvoiceTo: ["emailsToSendInvoiceTo"],
            billingAdmin: "billingAdmin",
            lastSavedTimestamp: 1646870400000,
            contactOrgListPermissions: {
                key: {
                    defaultPermissionSetName: "defaultPermissionSetName",
                    aclEntries: [{ userKey: "userKey", permissionSetName: "permissionSetName" }],
                },
            },
            contactSettings: {
                fields: {
                    key: {
                        name: "name",
                        key: "key",
                        type: "TEXT_INPUT",
                        lastDefaultValueUpdatedTimestamp: 1646870400000,
                        lastUpdatedTimestamp: 1646870400000,
                    },
                },
            },
            organizationSettings: {
                fields: {
                    key: {
                        name: "name",
                        key: "key",
                        type: "TEXT_INPUT",
                        lastDefaultValueUpdatedTimestamp: 1646870400000,
                        lastUpdatedTimestamp: 1646870400000,
                    },
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v2/teams")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.team.createTeam({
            name: "name",
            members: [{}],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTeam", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            key: "key",
            creationDate: 1646870400000,
            creator: "creator",
            members: [
                {
                    userKey: "userKey",
                    role: "Member",
                    inviteDate: 1646870400000,
                    inviteStatus: "Pending",
                    displayName: "displayName",
                    email: "email",
                    fullName: "fullName",
                    givenName: "givenName",
                    image: "image",
                    userType: "userType",
                    emailSharing: "None",
                },
            ],
            name: "name",
            sharingRestrictedToTeam: true,
            automaticallyApproveJoinRequests: true,
            automaticallySendInvoiceEmails: true,
            emailsToSendInvoiceTo: ["emailsToSendInvoiceTo"],
            billingAdmin: "billingAdmin",
            lastSavedTimestamp: 1646870400000,
            contactOrgListPermissions: {
                key: {
                    defaultPermissionSetName: "defaultPermissionSetName",
                    aclEntries: [{ userKey: "userKey", permissionSetName: "permissionSetName" }],
                },
            },
            contactSettings: {
                fields: {
                    key: {
                        name: "name",
                        key: "key",
                        type: "TEXT_INPUT",
                        lastDefaultValueUpdatedTimestamp: 1646870400000,
                        lastUpdatedTimestamp: 1646870400000,
                    },
                },
            },
            organizationSettings: {
                fields: {
                    key: {
                        name: "name",
                        key: "key",
                        type: "TEXT_INPUT",
                        lastDefaultValueUpdatedTimestamp: 1646870400000,
                        lastUpdatedTimestamp: 1646870400000,
                    },
                },
            },
        };

        server.mockEndpoint().get("/v2/teams/teamKey").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.team.getTeam({
            teamKey: "teamKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateTeam", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            key: "key",
            creationDate: 1646870400000,
            creator: "creator",
            members: [
                {
                    userKey: "userKey",
                    role: "Member",
                    inviteDate: 1646870400000,
                    inviteStatus: "Pending",
                    displayName: "displayName",
                    email: "email",
                    fullName: "fullName",
                    givenName: "givenName",
                    image: "image",
                    userType: "userType",
                    emailSharing: "None",
                },
            ],
            name: "name",
            sharingRestrictedToTeam: true,
            automaticallyApproveJoinRequests: true,
            automaticallySendInvoiceEmails: true,
            emailsToSendInvoiceTo: ["emailsToSendInvoiceTo"],
            billingAdmin: "billingAdmin",
            lastSavedTimestamp: 1646870400000,
            contactOrgListPermissions: {
                key: {
                    defaultPermissionSetName: "defaultPermissionSetName",
                    aclEntries: [{ userKey: "userKey", permissionSetName: "permissionSetName" }],
                },
            },
            contactSettings: {
                fields: {
                    key: {
                        name: "name",
                        key: "key",
                        type: "TEXT_INPUT",
                        lastDefaultValueUpdatedTimestamp: 1646870400000,
                        lastUpdatedTimestamp: 1646870400000,
                    },
                },
            },
            organizationSettings: {
                fields: {
                    key: {
                        name: "name",
                        key: "key",
                        type: "TEXT_INPUT",
                        lastDefaultValueUpdatedTimestamp: 1646870400000,
                        lastUpdatedTimestamp: 1646870400000,
                    },
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v2/teams/teamKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.team.updateTeam({
            teamKey: "teamKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listCurrentUsersTeams", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            hasNextPage: true,
            results: [
                {
                    key: "key",
                    creationDate: 1646870400000,
                    creator: "creator",
                    members: [
                        {
                            userKey: "userKey",
                            role: "Member",
                            inviteDate: 1646870400000,
                            inviteStatus: "Pending",
                            emailSharing: "None",
                        },
                    ],
                    name: "name",
                    sharingRestrictedToTeam: true,
                    automaticallyApproveJoinRequests: true,
                    automaticallySendInvoiceEmails: true,
                    emailsToSendInvoiceTo: ["emailsToSendInvoiceTo"],
                    billingAdmin: "billingAdmin",
                    lastSavedTimestamp: 1646870400000,
                    contactOrgListPermissions: {
                        key: { aclEntries: [{ userKey: "userKey", permissionSetName: "permissionSetName" }] },
                    },
                    contactSettings: {
                        fields: {
                            key: {
                                name: "name",
                                key: "key",
                                type: "TEXT_INPUT",
                                lastDefaultValueUpdatedTimestamp: 1646870400000,
                                lastUpdatedTimestamp: 1646870400000,
                            },
                        },
                    },
                    organizationSettings: {
                        fields: {
                            key: {
                                name: "name",
                                key: "key",
                                type: "TEXT_INPUT",
                                lastDefaultValueUpdatedTimestamp: 1646870400000,
                                lastUpdatedTimestamp: 1646870400000,
                            },
                        },
                    },
                },
            ],
        };

        server.mockEndpoint().get("/v2/users/me/teams").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.team.listCurrentUsersTeams();
        expect(response).toEqual(rawResponseBody);
    });
});
