// This file was auto-generated by Fern from our API Definition.

import { StreakClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UsersClient", () => {
    test("getCurrentUser", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            email: "email",
            creationTimestamp: 1646870400000,
            lastUpdatedTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastSeenTimestamp: 1646870400000,
            googleProfileId: "googleProfileId",
            googleProfilePhotoUrl: "googleProfilePhotoUrl",
            googleProfileLink: "googleProfileLink",
            googleProfileFullName: "googleProfileFullName",
            googleProfileFirstName: "googleProfileFirstName",
            googleProfileLastName: "googleProfileLastName",
            timezoneId: "timezoneId",
            userType: "HUMAN",
            securityReportOnTeamsPipelines: true,
            externalSharingRestrictionOnTeamsPipelines: true,
            automaticallySendInvoiceEmails: true,
            emailsToSendInvoiceTo: ["emailsToSendInvoiceTo"],
            customerSpecifiedInvoiceData: "customerSpecifiedInvoiceData",
            firstOauthTimestamp: 1646870400000,
            wantsTaskDigestEmail: true,
            displayName: "displayName",
            key: "key",
        };

        server.mockEndpoint().get("/v1/users/me").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.getCurrentUser();
        expect(response).toEqual(rawResponseBody);
    });

    test("getUserByKey", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            email: "email",
            creationTimestamp: 1646870400000,
            lastUpdatedTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastSeenTimestamp: 1646870400000,
            googleProfileId: "googleProfileId",
            googleProfilePhotoUrl: "googleProfilePhotoUrl",
            googleProfileLink: "googleProfileLink",
            googleProfileFullName: "googleProfileFullName",
            googleProfileFirstName: "googleProfileFirstName",
            googleProfileLastName: "googleProfileLastName",
            timezoneId: "timezoneId",
            userType: "HUMAN",
            securityReportOnTeamsPipelines: true,
            externalSharingRestrictionOnTeamsPipelines: true,
            automaticallySendInvoiceEmails: true,
            emailsToSendInvoiceTo: ["emailsToSendInvoiceTo"],
            customerSpecifiedInvoiceData: "customerSpecifiedInvoiceData",
            firstOauthTimestamp: 1646870400000,
            wantsTaskDigestEmail: true,
            displayName: "displayName",
            key: "key",
        };

        server.mockEndpoint().get("/v1/users/userKey").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.users.getUserByKey({
            userKey: "userKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateUserByKey", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            email: "email",
            creationTimestamp: 1646870400000,
            lastUpdatedTimestamp: 1646870400000,
            lastSavedTimestamp: 1646870400000,
            lastSeenTimestamp: 1646870400000,
            googleProfileId: "googleProfileId",
            googleProfilePhotoUrl: "googleProfilePhotoUrl",
            googleProfileLink: "googleProfileLink",
            googleProfileFullName: "googleProfileFullName",
            googleProfileFirstName: "googleProfileFirstName",
            googleProfileLastName: "googleProfileLastName",
            timezoneId: "timezoneId",
            userType: "HUMAN",
            securityReportOnTeamsPipelines: true,
            externalSharingRestrictionOnTeamsPipelines: true,
            automaticallySendInvoiceEmails: true,
            emailsToSendInvoiceTo: ["emailsToSendInvoiceTo"],
            customerSpecifiedInvoiceData: "customerSpecifiedInvoiceData",
            firstOauthTimestamp: 1646870400000,
            wantsTaskDigestEmail: true,
            displayName: "displayName",
            key: "key",
        };

        server
            .mockEndpoint()
            .post("/v1/users/userKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.updateUserByKey({
            userKey: "userKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAllUsersOnTeam", async () => {
        const server = mockServerPool.createServer();
        const client = new StreakClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hasNextPage: true,
            results: [
                {
                    email: "email",
                    creationTimestamp: 1646870400000,
                    lastUpdatedTimestamp: 1646870400000,
                    lastSavedTimestamp: 1646870400000,
                    lastSeenTimestamp: 1646870400000,
                    googleProfileId: "googleProfileId",
                    googleProfilePhotoUrl: "googleProfilePhotoUrl",
                    googleProfileLink: "googleProfileLink",
                    googleProfileFullName: "googleProfileFullName",
                    googleProfileFirstName: "googleProfileFirstName",
                    googleProfileLastName: "googleProfileLastName",
                    timezoneId: "timezoneId",
                    userType: "HUMAN",
                    securityReportOnTeamsPipelines: true,
                    externalSharingRestrictionOnTeamsPipelines: true,
                    automaticallySendInvoiceEmails: true,
                    emailsToSendInvoiceTo: ["emailsToSendInvoiceTo"],
                    customerSpecifiedInvoiceData: "customerSpecifiedInvoiceData",
                    firstOauthTimestamp: 1646870400000,
                    wantsTaskDigestEmail: true,
                    displayName: "displayName",
                    key: "key",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/teams/teamKey/users")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.users.getAllUsersOnTeam({
            teamKey: "teamKey",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
