// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         pipelineKey: "pipelineKey",
 *         stageKey: "stageKey"
 *     }
 */
export interface GetV2PipelinesPipelineKeyStagesStageKeyRequest {
    pipelineKey: string;
    stageKey: string;
}
