// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         pipelineKey: "pipelineKey",
 *         stageKey: "stageKey"
 *     }
 */
export interface PipelineStageUpdate {
    pipelineKey: string;
    stageKey: string;
    /** Nonempty new stage name. */
    name?: string | null;
    /** Custom stage colors. Set both foregroundColor and backgroundColor to empty strings to reset to the pipeline theme. */
    color?: Streak.PipelineStageColor | null;
}
