// This file was auto-generated by Fern from our API Definition.

import type * as Streak from "../../../../index.js";

/**
 * @example
 *     {
 *         pipelineKey: "pipelineKey",
 *         name: "name"
 *     }
 */
export interface PipelineStageCreate {
    pipelineKey: string;
    /** Nonempty name of the new stage. */
    name: string;
    /** Custom stage colors. Omit or set to null to use the pipeline theme. */
    color?: Streak.PipelineStageColor | null;
}
