// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         boxKey: "boxKey"
 *     }
 */
export interface GetV1BoxesBoxKeyMdRequest {
    boxKey: string;
    /** A token cap for the entire document, counted with OpenAI's o200k_base encoding. It covers the box sections first, then uses the remaining tokens for the timeline. A marker shows where entries were left out. If the box does not fit under the cap, a 400 error shows the minimum it needs. Omit the cap to return the full box. */
    maxTokens?: number | null;
}
