// This file was auto-generated by Fern from our API Definition.

import { ApiKeysClient } from "./api/resources/apiKeys/client/Client.js";
import { BoxesClient } from "./api/resources/boxes/client/Client.js";
import { CommentsClient } from "./api/resources/comments/client/Client.js";
import { ContactClient } from "./api/resources/contact/client/Client.js";
import { MeetingsClient } from "./api/resources/meetings/client/Client.js";
import { OrganizationClient } from "./api/resources/organization/client/Client.js";
import { PipelineClient } from "./api/resources/pipeline/client/Client.js";
import { PipelineStageClient } from "./api/resources/pipelineStage/client/Client.js";
import { SearchClient } from "./api/resources/search/client/Client.js";
import { TasksClient } from "./api/resources/tasks/client/Client.js";
import { TeamClient } from "./api/resources/team/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace StreakClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class StreakClient {
    protected readonly _options: NormalizedClientOptions<StreakClient.Options>;
    protected _apiKeys: ApiKeysClient | undefined;
    protected _boxes: BoxesClient | undefined;
    protected _pipeline: PipelineClient | undefined;
    protected _search: SearchClient | undefined;
    protected _users: UsersClient | undefined;
    protected _comments: CommentsClient | undefined;
    protected _meetings: MeetingsClient | undefined;
    protected _tasks: TasksClient | undefined;
    protected _contact: ContactClient | undefined;
    protected _organization: OrganizationClient | undefined;
    protected _pipelineStage: PipelineStageClient | undefined;
    protected _team: TeamClient | undefined;

    constructor(options: StreakClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get apiKeys(): ApiKeysClient {
        return (this._apiKeys ??= new ApiKeysClient(this._options));
    }

    public get boxes(): BoxesClient {
        return (this._boxes ??= new BoxesClient(this._options));
    }

    public get pipeline(): PipelineClient {
        return (this._pipeline ??= new PipelineClient(this._options));
    }

    public get search(): SearchClient {
        return (this._search ??= new SearchClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    public get comments(): CommentsClient {
        return (this._comments ??= new CommentsClient(this._options));
    }

    public get meetings(): MeetingsClient {
        return (this._meetings ??= new MeetingsClient(this._options));
    }

    public get tasks(): TasksClient {
        return (this._tasks ??= new TasksClient(this._options));
    }

    public get contact(): ContactClient {
        return (this._contact ??= new ContactClient(this._options));
    }

    public get organization(): OrganizationClient {
        return (this._organization ??= new OrganizationClient(this._options));
    }

    public get pipelineStage(): PipelineStageClient {
        return (this._pipelineStage ??= new PipelineStageClient(this._options));
    }

    public get team(): TeamClient {
        return (this._team ??= new TeamClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
            },
            requestOptions,
        );
    }
}
