// This file was auto-generated by Fern from our API Definition.

export const StreakEnvironment = {
    Default: "https://api.streak.com/api",
} as const;

export type StreakEnvironment = typeof StreakEnvironment.Default;
