// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userKey: "userKey"
 *     }
 */
export interface GetV1UsersUserKeyRequest {
    userKey: string;
}
