// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         userKey: "userKey"
 *     }
 */
export interface UserUpdateBody {
    userKey: string;
    /** IANA timezone identifier for the user, such as America/Los_Angeles. */
    timezoneId?: string | null;
    /** Given name for the user. */
    firstName?: string | null;
    /** Family name for the user. */
    lastName?: string | null;
    /** Whether invoice emails should be sent automatically. */
    automaticallySendInvoiceEmails?: boolean | null;
    /** Who should receive invoices */
    emailsToSendInvoiceTo?: string[] | null;
    /** Custom data that should be shown on the invoice */
    customerSpecifiedInvoiceData?: string | null;
}
