# This workflow is triggered when a GitHub release is created.
# It can also be run manually to re-publish to JSR in case it failed for some reason.
# You can run this workflow by navigating to https://www.github.com/StreakYC/streak-client-typescript/actions/workflows/publish-jsr.yml
name: Publish JSR
on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish to JSR
        run: |
          bash ./bin/publish-jsr
        env:
          JSR_TOKEN: ${{ secrets.STREAK_JSR_TOKEN || secrets.JSR_TOKEN }}
